/* Pixel-staged arcade scenes. Fixed viewport, authored motion, portraits, no movie editor. */
(function(root){'use strict';
const W=960,H=360,clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),mix=(a,b,t)=>a+(b-a)*t;
function rect(c,x,y,w,h,color){c.fillStyle=color;c.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h));}
function lineCart(c,x,y){rect(c,x-5,y-2,10,4,'#a5b6c2');}
function label(c,text,x,y,size=12,color='#e5d6bd',align='left'){c.font='bold '+size+'px monospace';c.textAlign=align;c.fillStyle=color;c.fillText(text,x,y);}
function position(item,t){const m=item.motion;if(!m)return {x:item.x||0,y:item.y??318,progress:1};const p=clamp((t-(m.start||0))/(m.duration||1),0,1);return {x:mix(m.fromX??item.x,m.toX??item.x,p),y:mix(m.fromY??item.y??318,m.toY??item.y??318,p)-Math.sin(p*Math.PI)*(m.arc||0),progress:p};}
class ScenePlayer{
 constructor(o){this.o=o;this.active=false;this.paused=false;this.loading=false;this.queue=[];this.serial=0;this.index=0;this.time=0;this.totalTime=0;this.imageCache=new Map();this.imageJobs=new Map();this.assetErrors=[];this.completed=new Set();this.actorStates=[];this._build();}
 _build(){const section=document.createElement('section');section.id='cutscene';section.className='screen';section.hidden=true;section.setAttribute('aria-label','Story cutscene');
 section.innerHTML='<div class="scene-frame"><canvas id="sceneSprites" width="960" height="360" aria-label="Pixel-art scene staging"></canvas></div><div class="scene-topline"><span class="scene-chapter"></span><div class="scene-tools"><button id="scenePause" aria-label="Pause cutscene">PAUSE</button><button id="sceneSkip">SKIP</button></div></div><div class="scene-copy"><div class="scene-portrait-frame"><img id="scenePortrait" alt="" data-empty="true"></div><div id="sceneSpeaker"></div><p id="sceneDialogue" aria-live="polite"></p><div class="scene-bottomline"><span id="scenePosition"></span><button id="sceneAdvance" class="primary">CONTINUE</button></div></div><div class="scene-paused" hidden>INTERMISSION<br><small>Select RESUME or press P / controller Start.</small></div>';
 document.body.appendChild(section);this.el=section;this.frame=section.querySelector('.scene-frame');this.canvas=section.querySelector('canvas');this.chapter=section.querySelector('.scene-chapter');this.speaker=section.querySelector('#sceneSpeaker');this.dialogue=section.querySelector('#sceneDialogue');this.portrait=section.querySelector('#scenePortrait');this.position=section.querySelector('#scenePosition');this.next=section.querySelector('#sceneAdvance');this.pauseButton=section.querySelector('#scenePause');this.pausedLabel=section.querySelector('.scene-paused');this.next.onclick=()=>this.advance();section.querySelector('#sceneSkip').onclick=()=>this.skip();this.pauseButton.onclick=()=>this.togglePause();section.addEventListener('pointerdown',e=>e.stopPropagation());}
 _warm(name){if(!name)return Promise.resolve();if(this.imageJobs.has(name))return this.imageJobs.get(name);const im=new Image();this.imageCache.set(name,im);const job=new Promise((resolve,reject)=>{im.onload=async()=>{try{if(typeof im.decode==='function')await im.decode();resolve(im);}catch(error){this.imageJobs.delete(name);this.imageCache.delete(name);reject(error);}};im.onerror=()=>{this.assetErrors.push(name);this.imageJobs.delete(name);this.imageCache.delete(name);reject(new Error('Scene artwork download failed: '+name));};im.src=this.o.resolve(name);});this.imageJobs.set(name,job);return job;}
 prepare(scene){const dep=CriticCutscenes.dependencies(scene.id,this.o.character(),this.o.meta());return Promise.all(dep.images.map(name=>this._warm(name)));}
 play(scene,onComplete){if(!scene||!Array.isArray(scene.shots)){onComplete?.({missing:true});return false;}const entry={scene,onComplete,done:false};if(this.active){this.queue.push(entry);return true;}this._begin(entry);return true;}
 _begin(entry){this.entry=entry;this.scene=CriticCutscenes.resolveScene(entry.scene,this.o.character());this.shots=this.scene.shots;this.index=0;this.time=this.totalTime=0;this.emissionTimelines=new Map();this.paused=false;this.active=true;this.loading=true;const serial=++this.serial;this.el.hidden=false;this.el.classList.toggle('world-stage',!!this.scene.worldStage);this.worldActors=new Map();this.o.beginWorldScene?.(this.scene);this.chapter.textContent=this.scene.title||this.scene.id;this.pauseButton.textContent='PAUSE';this.pausedLabel.hidden=true;this.o.clearInput();this.o.onOpen?.(this.scene);if(this.scene.music)this.o.music(this.scene.music);if(!this.shots.length){this.finish(false);return;}this._shot();this.prepare(entry.scene).then(()=>{if(!this.active||this.serial!==serial)return;this.loading=false;this.next.disabled=this.paused;this.position.textContent=(this.index+1)+' / '+this.shots.length;this.update(0);}).catch(error=>{if(!this.active||this.serial!==serial)return;this.loading=true;this.next.disabled=true;this.position.textContent='SCENE DOWNLOAD FAILED / SKIP TO CONTINUE';this.o.onError?.(error);});}
 _shot(){this.shot=this.shots[this.index];this.time=0;const s=this.shot;if(s.gameplayEntry){this.finish(false,'gameplayEntry');return;}if(s.emissionGroup&&!this.emissionTimelines.has(s.emissionGroup))this.emissionTimelines.set(s.emissionGroup,this.totalTime);this.speaker.textContent=s.speaker||'';this.dialogue.textContent=s.dialogue||s.caption||s.objective||'';this.position.textContent=this.loading?'PREPARING SCENE':(this.index+1)+' / '+this.shots.length;this.next.disabled=this.paused||this.loading;this.next.textContent='CONTINUE';this.portrait.dataset.empty='true';this.el.querySelector('.scene-copy').hidden=!(s.dialogue||s.caption||s.objective||s.portrait||s.speaker);this.el.classList.toggle('visual-only',this.el.querySelector('.scene-copy').hidden);this.o.clearInput();if(s.music)this.o.music(s.music);if(s.sound)this.o.sound(s.sound);this.update(0);}
 advance(){if(!this.active||this.paused||this.loading||this.time<(this.shot.minTime??.2))return false;this.index++;if(this.index>=this.shots.length)this.finish(false);else this._shot();return true;}
 skip(){if(!this.active)return false;this.finish(true);return true;}
 finish(skipped,reason=skipped?'skip':'watched'){const entry=this.entry;if(!entry||entry.done)return;entry.done=true;this.o.finishWorldScene?.(this.scene,skipped);this.active=false;this.paused=this.loading=false;this.el.hidden=true;this.o.clearInput();this.completed.add(entry.scene.id);this.lastCompletion={id:entry.scene.id,skipped:!!skipped,reason,shotId:this.shot?.id||null};entry.onComplete?.({...this.lastCompletion});
 // Completion can idempotently spawn the next boss and begin its scene. Preserve it.
 if(this.active||this.entry!==entry)return;if(this.queue.length)this._begin(this.queue.shift());else this.o.onIdle?.();}
 togglePause(force){if(!this.active)return;this.paused=typeof force==='boolean'?force:!this.paused;this.pauseButton.textContent=this.paused?'RESUME':'PAUSE';this.pausedLabel.hidden=!this.paused;this.next.disabled=this.paused||this.loading;this.o.clearInput();this.o.onPause?.(this.paused,this.scene.music);}
 key(e){if(!this.active)return false;const advance=['Enter','Space','KeyJ','KeyX','KeyZ'],skip=['Escape','Backspace'];if(!advance.includes(e.code)&&!skip.includes(e.code)&&e.code!=='KeyP')return false;e.preventDefault();if(e.repeat)return true;const activate=e.code==='Enter'||e.code==='Space';if(skip.includes(e.code)||activate&&e.target?.id==='sceneSkip')this.skip();else if(e.code==='KeyP'||activate&&e.target?.id==='scenePause')this.togglePause();else this.advance();return true;}
 controller(s){if(!this.active)return;if(s.pressed.back)this.skip();else if(s.pressed.pause)this.togglePause();else if(s.pressed.confirm||s.pressed.attack)this.advance();}
 update(dt){if(!this.active||!this.shot)return;if(!this.paused&&!this.loading){this.time+=dt;this.totalTime+=dt;}this._draw();this._portrait();this.el.querySelector('.scene-portrait-frame').hidden=this.portrait.dataset.empty==='true';if(this.shot.auto&&!this.paused&&!this.loading&&this.time>=this.shot.auto){this.index++;if(this.index>=this.shots.length)this.finish(false);else this._shot();}}
 _portrait(){const s=this.shot,id=s.portrait||({JAY:'jay',DUKE:'duke',MARTY:'marty',FRANKLIN:'franklin',PROJECTIONIST:'projectionist','PIZZERIA HEADLINER':'pizzeria','CINEMA HEADLINER':'pizzeria','VIOLENT AUSTRIAN RABBI':'pizzeria',SPIKE:'spike'}[s.speaker]);this.currentPortrait={id:id||null,expression:s.expression||'neutral',path:null};if(!id){this.portrait.dataset.empty='true';return;}const frames=CriticCutscenes.portraitFrames(this.o.meta(),id,s.expression||'neutral');let path=CriticCutscenes.portraitPath(this.o.meta(),id,s.expression||'neutral');if(frames.length){let ms=(this.time*1000)%frames.reduce((sum,f)=>sum+(f.ms||167),0);for(const f of frames){path=f.image;ms-=f.ms||167;if(ms<0)break;}}this.currentPortrait.path=path;const im=this.imageCache.get(path);if(im?.complete&&im.naturalWidth){const src=this.o.resolve(path);if(this.portrait.getAttribute('src')!==src)this.portrait.src=src;this.portrait.alt=(s.speaker||id)+' portrait';this.portrait.dataset.empty='false';}else this.portrait.dataset.empty='true';}
 _draw(){if(this.scene.worldStage&&this.o.drawWorldScene){this.o.drawWorldScene(this);return;}const c=this.canvas.getContext('2d');c.imageSmoothingEnabled=false;c.clearRect(0,0,W,H);this.actorStates=[];this.boothState=null;const s=this.shot,t=this.time,environment=s.environment||this.scene.environment||'broadway',r=this.o.renderer();c.save();const shake=!this.o.settings().reducedMotion&&s.shake&&t<s.shake?Math.round(Math.sin(t*53)*4*(1-t/s.shake)):0;c.translate(shake,0);this._environment(c,environment,s);const bg=Object.prototype.hasOwnProperty.call(s,'background')?s.background:this.scene.background;if(bg){const im=this.imageCache.get(bg);if(im?.complete&&im.naturalWidth)this._background(c,im);}
 this._architecture(c,environment,s);this._screens(c,s);this._cage(c,s.cage,false);if(s.circuits!==undefined)this._circuits(c,s.circuits);this._actors(c,s.actors||[],r);this._emissions(c,s.emissions||[],r);this._cage(c,s.cage,true);if(s.curtainReveal&&t<s.curtainReveal){const p=clamp(t/s.curtainReveal,0,1),a=s.cage;rect(c,a.x-a.w/2-6,a.y-a.h-8,(a.w+12)*(1-p),a.h+12,'#47223e');}
 if(s.alarm){const on=Math.floor(t*4)%2===0;rect(c,866,30,22,9,on?'#ffbf76':'#823d49');rect(c,62,30,22,9,on?'#ffbf76':'#823d49');if(on){c.globalAlpha=.08;rect(c,0,0,W,H,'#ff746a');c.globalAlpha=1;}}
 if(s.glass){for(let i=0;i<9;i++){const progress=clamp((t-.35)/.8,0,1);rect(c,40+i*16-progress*90,155+i%3*18+progress*140,5,3,'#bce7ed');}}
 if(s.destination||this.scene.destination){const destination=s.destination||this.scene.destination;rect(c,740,283,209,29,'#0a1524');label(c,destination,940,303,11,'#f7d58d','right');label(c,'→',939,326,21,'#b6ecdc','right');}
 if(s.objective){rect(c,264,10,438,31,'#0c1b32');label(c,s.objective,483,31,14,'#ffe0a4','center');}
 if(s.flash&&!this.o.settings().reducedMotion&&t<s.flash){c.globalAlpha=1-t/s.flash;rect(c,0,0,W,H,'#e8fcff');c.globalAlpha=1;}c.restore();}
 _background(c,im){const ratio=W/H;let sw=im.naturalWidth,sh=sw/ratio,sx=0,sy=0;if(sh>im.naturalHeight){sh=im.naturalHeight;sw=sh*ratio;sx=(im.naturalWidth-sw)/2;}else sy=clamp(im.naturalHeight*.75-sh*(318/H),0,im.naturalHeight-sh);c.drawImage(im,sx,sy,sw,sh,0,0,W,H);}
 _environment(c,kind,s){const colors={studio:['#112137','#223f56','#2e4053'],broadway:['#12213c','#33465c','#273746'],subway:['#152b37','#3c5259','#283d48'],rooftop:['#18233e','#364258','#2c374a'],theater:['#241936','#51405a','#2b2940'],cinema:['#141c34','#283c5a','#293349'],pizzeria:['#291e2d','#58454d','#3a343f'],broadcast:['#101e30','#223b4c','#293c4b']}[kind]||['#132237','#3b465d','#293649'];rect(c,0,0,W,100,colors[0]);rect(c,0,100,W,210,colors[1]);rect(c,0,310,W,50,colors[2]);for(let x=0;x<W;x+=80)rect(c,x,309,2,51,'#526273');for(let y=320;y<H;y+=17)rect(c,0,y,W,2,'#182736');
 if(kind==='broadway'||kind==='theater'||kind==='pizzeria'){for(let x=0;x<W;x+=190){rect(c,x+4,30,180,272,kind==='theater'?'#392c46':'#293441');for(let y=45;y<175;y+=54)for(let xx=x+18;xx<x+160;xx+=52){rect(c,xx,y,34,43,'#101e31');rect(c,xx+4,y+4,25,31,kind==='theater'?'#88657e':'#59757c');}rect(c,x+13,209,165,79,'#132332');rect(c,x+19,216,66,67,'#3c6470');rect(c,x+95,216,66,67,'#34515d');}rect(c,0,290,W,20,'#5b626a');}
 if(kind==='broadway'){rect(c,95,32,235,145,'#263c55');rect(c,108,43,208,110,'#0a1a2b');label(c,'PHILLIPS NETWORK',210,71,15,'#9be6de','center');label(c,'COMING ATTRACTIONS',210,111,15,'#f2dcaa','center');rect(c,0,179,W,13,'#47556b');}
 if(kind==='subway'){rect(c,0,43,W,249,'#54707b');for(let y=48;y<274;y+=24){rect(c,0,y,W,2,'#283f4c');for(let x=(y/24)%2*24;x<W;x+=48)rect(c,x,y,2,24,'#3c5660');}rect(c,345,50,593,217,'#0a1526');for(let x=350;x<960;x+=126){rect(c,x,71,117,186,'#71868c');rect(c,x+7,79,104,100,'#243d4c');rect(c,x+47,180,22,73,'#50606b');}for(let x=60;x<W;x+=250){rect(c,x,20,26,283,'#253c48');rect(c,x+4,20,5,283,'#738e96');}rect(c,0,292,W,13,'#b1a978');label(c,'UPTOWN EXPRESS',174,80,15,'#f0e7bb','center');}
 if(kind==='rooftop'){rect(c,0,55,W,190,'#192b44');for(let x=0;x<W;x+=57){rect(c,x,160-(x%93),51,141+(x%93),'#24364c');for(let y=190;y<279;y+=20)rect(c,x+7,y,4,6,'#c5a582');}rect(c,0,282,W,26,'#596370');rect(c,730,82,125,164,'#534b53');rect(c,716,70,154,16,'#29323f');for(let x=735;x<849;x+=13)rect(c,x,86,3,153,'#877478');rect(c,65,217,167,87,'#53616b');for(let x=73;x<223;x+=11)rect(c,x,225,4,61,'#222f3e');label(c,'ROOF ACCESS',440,269,12,'#d1d9ce','center');}
 if(kind==='theater'){rect(c,298,75,330,74,'#864d68');rect(c,305,83,315,57,'#182039');label(c,'PALACE CINEMA',462,119,22,'#ffe3a5','center');for(let x=305;x<620;x+=20){rect(c,x,76,5,5,'#ffe7b1');rect(c,x,144,5,5,'#ffe7b1');}for(let x=335;x<590;x+=52)rect(c,x,175,43,115,'#653946');rect(c,85,151,114,129,'#816847');rect(c,93,159,98,97,'#25374a');label(c,'BOX OFFICE',142,180,11,'#f5e2b8','center');}
 if(kind==='cinema'){rect(c,48,46,384,210,'#080f24');rect(c,59,56,362,189,'#abbacb');rect(c,28,29,25,246,'#783b51');rect(c,429,29,24,246,'#783b51');for(let y=263;y<301;y+=20)for(let x=8;x<W;x+=48){rect(c,x,y,37,21,'#663f54');rect(c,x-3,y+18,43,5,'#25283d');}rect(c,506,43,402,166,'#25374f');label(c,'PROJECTION BOOTH',707,63,13,'#b1cee1','center');}
 if(kind==='pizzeria'){rect(c,290,123,632,54,'#762f3b');label(c,'PIZZERIA',570,159,25,'#f4dbb4','center');for(let x=300;x<920;x+=28)rect(c,x,180,28,18,(x/28)%2?'#afc6ae':'#be6258');}
 if(kind==='broadcast'||kind==='studio'){rect(c,412,216,438,75,'#163146');for(let x=432;x<835;x+=26){rect(c,x,236,12,8,s.powered?'#89e8ce':'#4f6677');rect(c,x,256,12,8,s.powered?'#deba90':'#3d5467');}rect(c,518,254,166,51,'#213447');label(c,'TRANSMISSION CORE',600,282,12,'#bec5d0','center');}}
 _architecture(c,kind,s){if(kind==='studio'){rect(c,26,51,111,164,'#09192b');rect(c,26,51,111,5,'#89aeb9');rect(c,26,211,111,5,'#89aeb9');rect(c,26,51,5,164,'#89aeb9');rect(c,132,51,5,164,'#89aeb9');if(!s.brokenWindow){rect(c,80,56,4,154,'#517382');rect(c,30,129,103,4,'#517382');}label(c,'COMING ATTRACTIONS',245,66,16,'#e8d7a7','center');if(s.chair&&!this.imageCache.get('cutscenes/jay-seated.webp')?.naturalWidth){rect(c,222,204,69,88,'#6f3e51');rect(c,213,278,86,21,'#9a5865');rect(c,221,297,7,21,'#24273a');rect(c,284,297,7,21,'#24273a');}}
 if(kind==='cinema'){this._booth(c,s);this._screenForeshadow(c,s);}
 if(kind==='pizzeria'){const open=s.door?.open?1:s.door?.opening?clamp(this.time/.8,0,1):0;rect(c,737,197,98,112,'#0c1825');rect(c,738,197,4,112,'#b49e82');rect(c,831,197,4,112,'#b49e82');rect(c,742+open*77,201,(1-open)*87,107,'#6f5748');if(open<.95)rect(c,812+open*10,253,5,10,'#e3c89a');}}
 _booth(c,s){const phase=s.booth?.phase||'off',active=s.booth?.active??1,im=this.imageCache.get('story/projection-woman-pixel.webp'),colors=['#e8ad71','#9be0db','#c2adf0'],progress=clamp(this.time/(s.auto||1.5),0,1),eyes=progress<.28?'left':progress<.56?'right':progress<.68?'blink':'settle';this.boothState={phase,active,eyes,progress};for(let i=0;i<3;i++){const x=536+i*112,y=82,w=88,h=88,on=phase!=='off'&&i===active;rect(c,x-6,y-6,w+12,h+12,'#738ba5');rect(c,x-2,y-2,w+4,h+4,'#142640');rect(c,x,y,w,h,on&&phase==='lit'?'#3a5874':'#070f22');c.save();c.beginPath();c.rect(x+4,y+4,w-8,h-8);c.clip();if(on&&phase==='shadow'){rect(c,x+20,y+8,50,87,'#080b19');const blink=eyes==='blink',height=blink?2:7,yy=y+26+(blink?3:0),offset=eyes==='left'?-3:eyes==='right'?3:-1;rect(c,x+24,yy,13,height,'#aac9e8');rect(c,x+52,yy,13,height,'#aac9e8');if(!blink){rect(c,x+29+offset,y+27,4,6,'#253256');rect(c,x+57+offset,y+27,4,6,'#253256');}}else if(on&&phase==='lit'&&im?.complete&&im.naturalWidth){const height=92,width=height*im.naturalWidth/im.naturalHeight;c.drawImage(im,x+w/2-width/2,y+4,width,height);}c.restore();rect(c,x-6,y+h-2,w+12,8,'#91a8be');rect(c,x+w/2-5,y+h+7,10,5,on?colors[i]:'#3a4b61');}}
 _screenForeshadow(c,s){if(!s.screenForeshadow)return;const r=this.o.renderer(),animation=typeof s.screenForeshadow==='string'?s.screenForeshadow:'screen-taunt';c.save();c.beginPath();c.rect(59,56,362,189);c.clip();rect(c,59,56,362,189,'#718fa6');this._sprite(c,r,'pizzeria-boss',animation,242,260,1,this.time,.8,.88);for(let y=60;y<245;y+=7)rect(c,59,y,362,1,'#52738d');c.restore();}

 _screens(c,s){if(s.redButton){c.fillStyle='#8996a2';c.beginPath();c.ellipse(626,254,30,13,0,0,Math.PI*2);c.fill();c.fillStyle='#f32d40';c.beginPath();c.ellipse(626,247,27,12,0,0,Math.PI*2);c.fill();c.strokeStyle='#ffd6be';c.lineWidth=2;c.stroke();}const screens=s.screens||this.scene.screens||[];for(let i=0;i<screens.length;i++){const a=screens[i];rect(c,a.x-5,a.y-5,a.w+10,a.h+10,'#486375');rect(c,a.x,a.y,a.w,a.h,s.powered?'#477e91':'#142b3f');rect(c,a.x+3,a.y+3,a.w-6,a.h-6,s.powered?'#79c4c0':'#071522');if(s.powered){const who=CriticCutscenes.cast[i%CriticCutscenes.cast.length],r=this.o.renderer();c.save();c.beginPath();c.rect(a.x+3,a.y+3,a.w-6,a.h-6);c.clip();this._sprite(c,r,who,'idle',a.x+a.w/2,a.y+a.h+5,1,this.totalTime,.35,.9);c.restore();for(let y=a.y+4;y<a.y+a.h;y+=7)rect(c,a.x+4,y,a.w-8,1,'#589597');}}}
 _actorFace(a,actors){if(a.face===-1||a.face===1)return {face:a.face,reason:'explicit'};const p=position(a,this.time),visible=actors.filter(item=>item!==a&&!item.hidden&&(!item.routes||item.routes.includes(this.o.character())));let target=a.lookAt;if(typeof target==='string'){const match=visible.find(item=>item.id===target);target=match?position(match,this.time).x:null;}else if(target&&typeof target==='object')target=target.x;if(typeof target==='number'&&Number.isFinite(target)&&Math.abs(target-p.x)>.01)return {face:target<p.x?-1:1,reason:'lookAt'};if(a.motion&&Math.abs((a.motion.toX??a.x)-(a.motion.fromX??a.x))>.01)return {face:a.motion.toX<a.motion.fromX?-1:1,reason:'motion'};const identities={JAY:'hero',FRANKLIN:'franklin',DUKE:'duke',MARTY:'marty',SPIKE:'spike','CINEMA HEADLINER':'pizzeria-boss','PIZZERIA HEADLINER':'pizzeria-boss','VIOLENT AUSTRIAN RABBI':'pizzeria-boss'},speaker=identities[this.shot.speaker],who=item=>item.character==='selected'?this.o.character():item.character;let candidate=visible.find(item=>speaker&&who(item)===speaker);if(!candidate)candidate=visible.filter(item=>['hero','franklin','duke','spike','pizzeria-boss'].includes(who(item))).sort((a,b)=>Math.abs(position(a,this.time).x-p.x)-Math.abs(position(b,this.time).x-p.x))[0];if(candidate){const x=position(candidate,this.time).x;if(Math.abs(x-p.x)>.01)return {face:x<p.x?-1:1,reason:speaker&&who(candidate)===speaker?'speaker':'major-actor'};}return {face:1,reason:'default'};}
 _actors(c,actors,r){for(const a of actors){if(a.hidden||a.routes&&!a.routes.includes(this.o.character()))continue;const who=a.character==='selected'?this.o.character():a.character,p=position(a,this.time),direction=this._actorFace(a,actors),anim=this.time>(a.after||Infinity)?a.afterAnimation||a.animation:a.animation||'idle';this.actorStates.push({id:a.id,character:who,animation:anim,x:p.x,y:p.y,progress:p.progress,visible:true,resolvedFace:direction.face,faceReason:direction.reason,...(a.emerging?{source:'cinema-screen'}:{})});const image=a.image&&this.imageCache.get(a.image);if(image?.complete&&image.naturalWidth){const h=a.imageHeight||image.naturalHeight,scale=h/image.naturalHeight,w=image.naturalWidth*scale,pivot=a.imagePivot||{x:image.naturalWidth/2,y:image.naturalHeight};c.drawImage(image,p.x-pivot.x*scale,p.y-pivot.y*scale,w,h);continue;}const age=a.motion?Math.max(0,this.time-(a.motion.start||0)):this.time,walk=a.motion&&p.progress>=1&&['walk','run'].includes(anim)?'idle':anim;c.save();if(a.emerging&&p.progress<.32){c.beginPath();c.rect(59,56,362,189);c.clip();}c.translate(p.x,p.y);if(a.rotate)c.rotate(a.rotate*Math.PI/180*clamp((this.time-.35)/.6,0,1));this._sprite(c,r,who,walk,0,0,direction.face,age,(a.scale||1)*(a.emerging?mix(.42,1,p.progress):1),1);c.restore();}}

 _sprite(c,r,who,animation,x,y,face,t,scale,alpha=1){if(!r)return;const bank=this.o.meta()?.characters?.[who];if(!bank)return;let name=animation;if(who==='franklin')name=Brawler.playerAnimation(who,name);if(!bank[name])name=bank.idle?'idle':Object.keys(bank)[0];r.shadow(c,who,name,x,y,face,t,0,scale,0,.3);r.sprite(c,who,name,x,y,face,t,0,{scale,alpha,loop:!!bank[name].loop});}
 _cage(c,cage,front){if(!cage)return;const a=position(cage,this.time),x=a.x-cage.w/2,y=a.y-cage.h;if(!front){rect(c,x-9,a.y+2,cage.w+18,8,'#748292');for(const wx of [15,cage.w-15]){c.fillStyle='#0a1423';c.beginPath();c.arc(x+wx,a.y+13,10,0,Math.PI*2);c.fill();lineCart(c,x+wx,a.y+13);}rect(c,x-5,y-5,cage.w+10,cage.h+7,'#1d283c');rect(c,x,y,cage.w,cage.h,'#0a172c');if(cage.carried){rect(c,x-47,y+68,46,5,'#8fa3b5');rect(c,x-50,y+67,5,15,'#a1b7c6');}return;}rect(c,x-3,y-3,cage.w+6,5,'#b5c3c8');rect(c,x-3,a.y-5,cage.w+6,7,'#9faeb7');rect(c,x-3,y,5,cage.h,'#8599aa');rect(c,x+cage.w-3,y,5,cage.h,'#b8c4c4');if(!cage.open)for(let n=18;n<cage.w;n+=20)rect(c,x+n,y+3,4,cage.h-8,'#a5b6c2');else{rect(c,x+cage.w+10,y+2,4,cage.h,'#a5b6c2');for(let n=19;n<62;n+=17)rect(c,x+cage.w+n,y+2,3,cage.h,'#829bab');}rect(c,x+cage.w/2-8,y+68,15,20,cage.open?'#91c8a9':'#d8b682');if(cage.carried)rect(c,x+7,a.y+2,cage.w-14,4,'#1a2130');}
 _emissions(c,emissions,r){const screens=this.shot.screens||this.scene.screens||[],group=this.shot.emissionGroup,clock=group?this.totalTime-(this.emissionTimelines.get(group)??this.totalTime):this.time,cast=[];
 for(const e of emissions){const t=clock-(e.start||0);if(t<0)continue;const a=screens[e.screen];if(!a)continue;const face=e.face===1||e.face===-1?e.face:e.toX<a.x+a.w/2?-1:1,duration=e.duration||1.3,p=clamp(t/duration,0,1),approach=e.approach,ap=approach?clamp((t-duration)/(approach.duration||1),0,1):0,action=this.shot.emissionActions?.[e.id]||this.shot.emissionActions?.['*'],step=action?clamp(this.time/(action.duration||1),0,1):0;
 const x=mix(a.x+a.w/2,e.toX,p)+(approach?mix(e.toX,approach.toX,ap)-e.toX:0)-(action?.advance||0)*step,y=mix(a.y+a.h,e.toY??318,p)-Math.sin(p*Math.PI)*36,scale=mix(.23,e.scale||.86,p);let animation=e.animation||'idle',age=t;
 if(approach&&p>=1){animation=ap<1?'walk':'idle';age=Math.max(0,t-duration);}if(action){animation=action.animation||animation;age=this.time;if(this.time>=(action.after??Infinity)){animation=action.afterAnimation||animation;age=Math.max(0,this.time-action.after);}}
 const bounds=r?.animationBounds?.(e.character,animation,face),worldBounds=bounds?{left:x+bounds.minX*scale,right:x+bounds.maxX*scale,top:y+bounds.minY*scale,bottom:y+bounds.maxY*scale}:null;
 cast.push({e,a,t,p,face,x,y,scale,animation,age});this.actorStates.push({id:e.id,character:e.character,animation,x,y,progress:p,approachProgress:ap,source:'screen-'+e.screen,visible:true,resolvedFace:face,faceReason:e.face===1||e.face===-1?'explicit':'motion',bounds:worldBounds});}
 // Floor depth orders the persistent crowd; the cage remains in its separate right-hand space.
 cast.sort((a,b)=>a.y-b.y);for(const item of cast){const {e,a,t,p,face,x,y,scale,animation,age}=item;if(p<.24){c.save();c.beginPath();c.rect(a.x-15,a.y-15,a.w+30,a.h+30);c.clip();this._sprite(c,r,e.character,animation,x,y,face,age,scale,1);c.restore();}else this._sprite(c,r,e.character,animation,x,y,face,age,scale,1);if(t<.22){rect(c,a.x-3,a.y-3,a.w+6,3,'#e7ffe6');rect(c,a.x-3,a.y+a.h,a.w+6,3,'#e7ffe6');}}}

 _circuits(c,count){const colors=['#e8ad71','#9be0db','#c2adf0'];for(let i=0;i<3;i++){const x=580+i*112,on=i<count;rect(c,x-12,278,24,41,'#172936');rect(c,x-8,283,16,19,on?colors[i]:'#405562');label(c,String(i+1),x,298,10,on?'#172936':'#899baa','center');rect(c,x-1,171,2,107,on?colors[i]:'#35475a');}}
 state(){const box=el=>{const b=el.getBoundingClientRect();return {x:b.x,y:b.y,width:b.width,height:b.height};};return {active:this.active,paused:this.paused,loading:this.loading,id:this.scene?.id||null,shotId:this.shot?.id||null,index:this.index,queued:this.queue.length,completed:[...this.completed],completion:this.lastCompletion?{...this.lastCompletion}:null,assetErrors:[...this.assetErrors],route:this.o.character(),speaker:this.shot?.speaker||'',dialogue:this.shot?.dialogue||'',portrait:this.currentPortrait,booth:this.boothState?{...this.boothState}:null,actors:this.actorStates.map(a=>({...a})),martyVisible:this.actorStates.some(a=>a.character==='marty'),emergingCast:this.actorStates.filter(a=>a.source).map(a=>({...a})),bounds:{viewport:box(this.frame),dialogue:box(this.el.querySelector('.scene-copy')),portrait:box(this.el.querySelector('.scene-portrait-frame')),advance:box(this.next)},source:{width:W,height:H}};}
}
root.CriticScenePlayer=ScenePlayer;
})(typeof globalThis!=='undefined'?globalThis:this);
