'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),B=require('../engine.js');
const results=[];
function test(name,fn){try{results.push({name,passed:true,details:fn()});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:String(e.stack)});console.error('FAIL',name,e.message);}}
function tick(g,n,input={}){for(let i=0;i<n;i++)g.step(1/120,typeof input==='function'?input(i):input);}
function stage(index){const g=new B.Game();g.start({version:4,stage:index,nextGate:2,lives:3,meter:35,stage4Eligible:true});g.activeGate=2;g.p.x=2180;g.p.y=407;g.camera=1820;g.enemies=[];g.props=[];g.events=[];return g;}
function visibleBoss(g){if(g.stage===4)require('./v9-fixtures').clearProjection(g);g.spawnBoss();const e=g.enemies[0];e.entry=null;e.hidden=false;e.targetable=true;e.state='seek';e.x=g.p.x+80;e.y=g.p.y;e.timer=e.animT=0;e.cooldown=0;return e;}
test('Campaign preserves the 12 authored opening fights and 39 original regular spawns',()=>{
 const original=[
  [['sherm-punch','sherm-punch'],['sherm-punch','sherm-shove','bear'],['sherm-punch','sherm-shove','striped']],
  [['sherm-punch','sherm-shove','sherm-slam'],['sherm-shove','sherm-punch','raptor'],['sherm-slam','sherm-punch','hippo','sherm-shove']],
  [['sherm-punch','sherm-shove','striped'],['sherm-slam','sherm-punch','bear'],['sherm-shove','sherm-slam','raptor','sherm-punch']],
  [['sherm-punch','sherm-slam','hippo'],['sherm-shove','sherm-punch','striped','sherm-slam'],['sherm-punch','sherm-shove','raptor','sherm-slam']]
 ];assert.deepStrictEqual(B.STAGES.slice(0,4).map(s=>s.waves),original);assert.equal(original.flat(2).length,39);
});
test('All new districts have a distinct scene, story purpose and recurring Shermometer majority',()=>{assert.equal(B.STAGES.length,7);assert.equal(new Set(B.STAGES.map(s=>s.scene)).size,7);for(const s of B.STAGES){assert(s.purpose);const enemies=s.waves.flat();assert(enemies.filter(k=>k.startsWith('sherm-')).length>enemies.length/2);}});
test('Only canonical names are exposed through legacy combat IDs',()=>{assert.equal(B.EINFO['sherm-punch'].name,'Shermometer v1');assert.equal(B.EINFO['sherm-shove'].name,'Shermometer v2');assert.equal(B.EINFO['sherm-slam'].name,'Shermometer v3');assert.equal(B.EINFO.striped.name,'Fred K');assert.equal(B.EINFO.raptor.name,'JP Raptor Esq');});
test('New content leaves accepted player hit timing, damage and reach unchanged',()=>{const base=JSON.parse(fs.readFileSync(path.join(__dirname,'v2-combat-baseline.json')));assert.deepStrictEqual(B.HITS,base.HITS);assert.deepStrictEqual(B.CHAIN,base.CHAIN);});
test('Stage 4 awards Franklin at its exit and continues to the cinema exactly once',()=>{const g=stage(3);const e=visibleBoss(g);g.registerHit(e,{damage:999,kb:0});g.nextGate=3;g.activeGate=-1;g.p.x=2800;g.advanceStage();assert.equal(g.mode,'stageclear');assert(g.franklinUnlocked);const events=g.drain();assert.equal(events.filter(x=>x.type==='unlock').length,1);g.advanceStage();assert.equal(g.drain().filter(x=>x.type==='unlock').length,0);assert(g.finishStageClear());assert.equal(g.stage,4);assert.equal(g.mode,'play');assert(!g.finishStageClear());assert(!g.lastUnlockEarned);});
test('A Stage 4 death does not block the campaign, but disqualifies its unlock challenge',()=>{const g=stage(3);g.recordDeath();const e=visibleBoss(g);g.registerHit(e,{damage:999,kb:0});g.advanceStage();assert.equal(g.mode,'stageclear');assert(!g.franklinUnlocked);g.finishStageClear();assert.equal(g.stage,4);});
test('Saved Franklin replay uses the alternate Stage 4 opponent after migration',()=>{const g=new B.Game();g.start({version:4,stage:3,nextGate:2,playerKind:'franklin',franklinUnlocked:true});g.activeGate=2;g.spawnBoss();assert.equal(g.playerKind,'franklin');assert.equal(g.enemies[0].kind,'sherm-slam');});
test('v2 and v3 checkpoints retain stage, score, lives and meter in the expanded schema',()=>{for(const version of [2,3]){const g=new B.Game();g.franklinUnlocked=true;g.start({version,stage:2,nextGate:1,score:777,lives:2,meter:81,time:44,deathsByStage:[1,2,3,0],playerKind:'franklin'});const s=g.snapshot();assert.equal(s.version,5);assert.equal(s.stage,2);assert.equal(s.nextGate,1);assert.equal(s.score,777);assert.equal(s.lives,2);assert.equal(s.meter,81);assert(s.franklinUnlocked);assert.equal(s.playerKind,'franklin');assert.equal(s.deathsByStage.length,7);}});
test('Previously completed v3 campaigns resume at the cinema with Franklin retained',()=>{const g=new B.Game();g.franklinUnlocked=true;g.start({version:3,stage:3,nextGate:3,bossDefeated:true,complete:true,score:5000,lives:2});assert.equal(g.stage,4);assert.equal(g.nextGate,0);assert.equal(g.score,5000);assert(g.franklinUnlocked);assert(!g.bossDefeated);assert(g.storyFlags['stage4-clear']);});
test('Expanded late-stage Continue retains story flags, unlock and checkpoint identity',()=>{const g=stage(5);g.storyCompleted('opening');g.storyCompleted('stage-06-intro');g.franklinUnlocked=true;g.checkpointSave();const h=new B.Game();h.start(JSON.parse(JSON.stringify(g.snapshot())));assert.equal(h.stage,5);assert.equal(h.nextGate,2);assert(h.storyFlags.opening);assert(h.storyFlags['stage-06-intro']);assert(h.franklinUnlocked);});
test('Stage story hooks are idempotent across repeats and serialized Continue',()=>{const g=stage(0);g.advanceStage();g.finishStageClear();assert.equal(g.drain().filter(e=>e.type==='story'&&e.id==='stage-02-intro').length,1);assert(!g.story('stage-02-intro'));const h=new B.Game();h.start(g.snapshot());assert(!h.story('stage-02-intro'));});
test('The projectionist locks her warning to the floor before launching a visible projectile',()=>{const g=stage(4);g.configureProjection();g.updateProjection(2.61);assert.equal(g.projection.phase,'shadow');g.updateProjection(1.16);assert.equal(g.projection.phase,'reveal');assert(g.projection.visible);assert.equal(g.projectiles.length,0);g.updateProjection(.56);const target={...g.projection.telegraph};assert.equal(g.projection.phase,'telegraph');assert(g.projection.visible);assert.equal(g.projectiles.length,0);const hp=g.p.hp;g.p.x+=80;g.updateProjection(1.16);assert.equal(g.projectiles.length,1);assert.equal(g.projectiles[0].targetX,target.x);assert.equal(g.p.hp,hp);g.updateProjectiles(.7);assert.equal(g.p.hp,hp);});
test('Staying inside the projection target incurs damage only when the reel arrives',()=>{const g=stage(4);g.configureProjection();g.updateProjection(2.7);g.updateProjection(1.16);g.updateProjection(.56);g.updateProjection(1.16);const hp=g.p.hp;g.updateProjectiles(.4);assert.equal(g.p.hp,hp);g.updateProjectiles(.31);assert.equal(g.p.hp,hp-11);assert.equal(g.projectiles.length,1);assert.equal(g.projectiles[0].phase,'bounce');assert.equal(g.p.action.name,'knockdown');g.updateProjectiles(.9);assert.equal(g.projectiles.length,0);});
test('An evasive slip avoids the incoming reel using the existing dodge immunity',()=>{const g=stage(4);g.launchProjectile('reel',g.p.x+150,158,g.p.x,g.p.y);g.p.action={name:'dodge',t:.2};g.updateProjectiles(.7);assert.equal(g.p.hp,100);});
test('Cinema cannot finish before remote circuits and headliner are defeated',()=>{const g=stage(4);assert(!g.spawnBoss());g.advanceStage();assert.equal(g.mode,'play');const boss=visibleBoss(g);g.advanceStage();assert.equal(g.mode,'play');g.registerHit(boss,{damage:9999,kb:0});g.advanceStage();assert.equal(g.mode,'stageclear');});
test('Booth shutdown cancels active reels and awards its story consequence once',()=>{const g=stage(4);g.configureProjection();g.launchProjectile('reel',2000,158,g.p.x,g.p.y);assert(g.disableProjection());assert(!g.disableProjection());assert.equal(g.projectiles.length,0);assert.equal(g.drain().filter(e=>e.type==='story'&&e.id==='boss-projection-defeat').length,1);});
test('Legacy Continue after headliner defeat restores remaining remote objectives',()=>{const g=stage(4);g.bossDefeated=true;g.bossSpawned=true;g.disableCircuit(0);const h=new B.Game();h.start(g.snapshot());h.spawnFight(2);assert(h.bossDefeated);assert.equal(h.projection.circuits.filter(c=>c.active).length,2);assert(!h.props.some(o=>o.kind==='circuit'));});
test('Cinema boss spawns once after projection and never duplicates its intro',()=>{const g=stage(4);assert(!g.spawnBoss());require('./v9-fixtures').clearProjection(g);assert(g.spawnBoss());assert(!g.spawnBoss());assert.equal(g.enemies.length,1);assert(!g.props.some(o=>o.kind==='circuit'));assert.equal(g.drain().filter(e=>e.type==='story'&&e.id==='boss-cinema-intro').length,1);});
test('Turkey Dinner is a distinct immediate heal and Trash Can keeps the legacy alias',()=>{const g=stage(5);g.p.hp=20;g.p.meter=30;g.activeGate=-1;g.nextGate=3;g.pickups=[{kind:'turkey-dinner',x:g.p.x,y:g.p.y,age:0}];g.step(1/120);assert.equal(g.p.hp,66);assert.equal(g.p.meter,42);assert.equal(g.pickups.length,0);assert.equal(g.drain().find(e=>e.type==='pickup').heal,46);assert.equal(B.PROPS.bin.name,B.PROPS['trash-can'].name);});
test('New physical bosses telegraph before contact and expose a recovery window',()=>{for(const index of [4,5]){const g=stage(index),e=visibleBoss(g);g.updateBoss(e,1/120);assert.equal(e.state,'windup');const hp=g.p.hp;g.updateBoss(e,e.move.wind-.02);assert.equal(g.p.hp,hp);g.updateBoss(e,.03);assert.equal(e.state,'attack');for(let i=0;i<240&&e.state==='attack';i++){g.updateBoss(e,1/120);g.updateProjectiles(1/120);}assert.equal(e.state,'recover');assert((e.move.recovery||B.BOSS_DEFINITIONS[e.kind].recovery)>=.7);}});
test('Environmental transmitter locks its warning lane and permits escape before contact',()=>{const g=stage(6);g.spawnBoss();g.updateBroadcastSummons(.01);const core=g.enemies[0];require('./v9-fixtures').advanceDevice(g,()=>g.broadcastSummons.phase==='shielded');g.updateMachine(core,4);assert(core.telegraph);g.updateMachine(core,.85);const y=core.telegraph.y;g.p.y=y+40;g.updateMachine(core,.51);assert.equal(g.p.hp,100);assert(core.telegraph.firing);g.updateMachine(core,.8);assert.equal(core.telegraph,null);});
test('Transmitter rejects shielded damage and accepts only its exposed round budget',()=>{const g=stage(6);g.spawnBoss();const e=g.enemies[0];assert(!g.registerHit(e,{damage:999,kb:0}));g.updateBroadcastSummons(.01);for(const foe of g.enemies.filter(e=>e.broadcastSummon))g.registerHit(foe,{damage:999,kb:0});require('./v9-fixtures').advanceDevice(g,()=>g.broadcastSummons.phase==='vulnerable');assert(g.registerHit(e,{damage:999,kb:0}));assert.equal(e.hp,200);assert(!g.registerHit(e,{damage:999,kb:0}));});
test('The final exit resolves Marty and the broadcast exactly once for either playable route',()=>{for(const character of ['hero','franklin']){const g=stage(6);g.franklinUnlocked=character==='franklin';g.playerKind=character;const e=visibleBoss(g);require('./v9-fixtures').defeatMachine(g);assert.equal(g.mode,'confrontation');assert(!g.dukeDefeated);g.finishDukeConfrontation();g.registerHit(g.enemies[0],{damage:9999,kb:100});for(let i=0;i<500;i++)g.step(1/120,{});g.nextGate=3;g.activeGate=-1;g.advanceStage();assert.equal(g.mode,'complete');assert(g.storyFlags.martyRescued);assert(g.storyFlags.broadcastStopped);const score=g.score;g.advanceStage();assert.equal(g.score,score);assert.equal(g.drain().filter(e=>e.type==='complete').length,1);assert(!g.lastUnlockEarned);}});
test('The complete seven-stage story is playable through combat inputs on Jay and Franklin routes',()=>{
 const reports=[];for(const character of ['hero','franklin']){const g=new B.Game();g.franklinUnlocked=character==='franklin';g.start(null,character);let ticks=0,retries=0;const seen=new Set(),bosses=new Set();
  for(;ticks<120*1500&&g.mode!=='complete';ticks++){
   if(g.mode==='confrontation')g.finishDukeConfrontation();if(g.mode==='gameover'){retries++;g.retry(true);}if(g.mode==='stageclear')g.finishStageClear();if(g.mode!=='play')continue;seen.add(g.stage);
   const p=g.p,targets=g.enemies.filter(e=>e.hp>0&&(e.kind!=='broadcast-rig'||e.targetable)).concat(g.props.filter(o=>['circuit','remote'].includes(o.kind)&&o.hp>0)).sort((a,b)=>Math.hypot(a.x-p.x,(a.y-p.y)*2)-Math.hypot(b.x-p.x,(b.y-p.y)*2));let input={};
   if(targets.length){const e=targets[0],dx=e.x-p.x,dy=e.y-p.y;if(e.boss)bosses.add(e.kind);input.mx=Math.abs(dx)>62?Math.sign(dx)*(Math.abs(dx)>150?1:.4):0;input.my=Math.abs(dy)>8?Math.sign(dy)*.55:0;input.attackPressed=Math.abs(dx)<122&&Math.abs(dy)<25&&ticks%12===0;input.attackHeld=Math.abs(dx)<116&&Math.abs(dy)<27;if(p.meter>=100&&targets.length>1&&!p.action)input.specialPressed=true;}else input.mx=1;
   g.step(1/120,input);g.drain();
  }
  assert.equal(g.mode,'complete');assert.equal(seen.size,7);assert(g.stats.kos>=71);assert(retries<5);assert(bosses.has('pizzeria-boss'));assert(bosses.has('spike'));assert(bosses.has('duke'));assert(bosses.has('broadcast-rig'));assert(!bosses.has(character==='franklin'?'franklin':'sherm-slam'));assert(g.storyFlags.martyRescued&&g.storyFlags.broadcastStopped);reports.push({character,seconds:g.t,retries,stages:seen.size,kos:g.stats.kos,bosses:[...bosses]});
 }return reports;
});
fs.writeFileSync(path.join(__dirname,'campaign-engine-results.json'),JSON.stringify({tests:results,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length},null,2));if(results.some(x=>!x.passed))process.exitCode=1;
