const assert=require('node:assert/strict');
const {CinematicCamera}=require('../engine.js');
const d=require('../data/cutscenes.js');
let count=0;function test(name,fn){fn();console.log('PASS',name);count++;}
test('Eased pan reaches target without overshoot; completion fires once',()=>{let done=0;const c=new CinematicCamera(120);c.shot('one',{x:720,y:10,zoom:1.04},{duration:1,onComplete:()=>done++});let last=120,steps=[];for(let i=0;i<120;i++){const p=c.update(1/60);assert(p.x>=last&&p.x<=720);steps.push(p.x-last);last=p.x;}assert.equal(c.pose.x,720);assert.equal(done,1);assert(steps[0]<steps[20]);assert(steps[59]<steps[40]);});
test('Retarget, pause and cancellation preserve displayed pose',()=>{const c=new CinematicCamera();c.shot('a',{x:500});c.update(.2);const x=c.pose.x;c.shot('b',{x:20});assert.equal(c.pose.x,x);c.update(0);assert.equal(c.pose.x,x);c.cancel();c.update(1);assert.equal(c.pose.x,x);});
test('Repeated shot keys cannot restart interpolation; reduced motion settles',()=>{const c=new CinematicCamera();for(let i=0;i<12;i++){c.shot('a',{x:300},{reduced:true});c.update(.02);}assert.equal(c.pose.x,300);assert(!c.active);});
test('Reunion remains first, Jay speaks on both routes, collapse cannot be advanced early',()=>{for(const route of ['hero','franklin']){const s=d.resolveScene(d.scenes.ending,route);assert.equal(s.shots[0].id,'marty-freed');assert.equal(s.shots.find(s=>s.id==='skyline-realization').speaker,'JAY');assert.equal(s.shots.find(s=>s.id==='skyline-realization').dialogue,"Oh my god, is that a plane?!? Hatchi Matchi!");assert(s.shots.find(s=>s.id==='skyline-collapse').minTime>=7);assert.equal(s.shots.at(-1).images.length,7);}});
test('Dialogue beat changes with the same target do not restart a pan',()=>{const c=new CinematicCamera();c.shot('first',{x:600},{duration:1});c.update(.3);const elapsed=c.elapsed;c.shot('second',{x:600,y:0,zoom:1});assert.equal(c.elapsed,elapsed);c.update(.7);assert.equal(c.pose.x,600);assert(!c.active);});
test('Every stage holds its opening and gates player entry on the cart exit',()=>{for(let n=1;n<=7;n++){const s=d.scenes['stage-0'+n+'-intro'];assert(s.stationaryOpening);assert(s.shots[0].awaitExit);assert(!s.shots[0].actors.some(a=>a.id==='player'));if(n>1)assert.equal(s.shots[1].id,'pursuit-entry');}});
test('Only the requested theater route line changes',()=>{assert(d.resolveScene(d.scenes['boss-projection-intro'],'hero').shots.some(s=>s.dialogue==='The remote to close the projection booth has to be around here somewhere...'));assert(d.resolveScene(d.scenes['boss-projection-intro'],'franklin').shots.some(s=>s.dialogue==='Lights first. Then the exit.'));});
console.log(count+' focused camera checks passed');
