'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path');const B=require('../engine.js');const results=[];
function test(name,fn){try{const details=fn();results.push({name,passed:true,details});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:String(e.stack)});console.log('FAIL',name,e.message);}}
function tick(g,n,input={}){for(let i=0;i<n;i++)g.step(1/120,input);}
function fourth(){const g=new B.Game();g.start({version:3,stage:3,nextGate:0,lives:3,meter:35,deathsByStage:[0,0,0,0],stage4Eligible:true});g.nextGate=3;g.activeGate=-1;g.p.x=2200;g.events=[];return g;}
function beatBoss(g){g.activeGate=2;g.spawnFranklin();const e=g.enemies[0];g.registerHit(e,{damage:999,kb:120,sound:'heavy'});g.hitstop=0;tick(g,95);assert.equal(g.nextGate,3);g.enemies=[];g.p.x=2800;g.advanceStage();return e;}
test('Shermometers dominate every stage and at least two thirds of the regular roster',()=>{let n=0,s=0;for(const stage of B.STAGES){const a=stage.waves.flat();n+=a.length;s+=a.filter(x=>x.startsWith('sherm-')).length;assert(a.filter(x=>x.startsWith('sherm-')).length>a.length/2);}assert(s/n>=2/3);return {shermometers:s,regularEnemies:n,share:s/n};});
test('All three Shermometer types and both new guest enemies occur in the campaign',()=>{const kinds=new Set(B.STAGES.flatMap(s=>s.waves.flat()));for(const k of ['sherm-punch','sherm-shove','sherm-slam','striped','raptor','bear','hippo'])assert(kinds.has(k));});
test('Franklin and legacy Elder never appear as ordinary wave enemies',()=>{const all=B.STAGES.flatMap(s=>s.waves.flat());assert(!all.some(s=>s.startsWith('franklin')||s.startsWith('elder')));assert(!B.EINFO.elder);});
test('Hero combo damage, reach, timing, and chain are byte-identical to v2 definitions',()=>{const expected=JSON.parse(fs.readFileSync(path.join(__dirname,'v2-combat-baseline.json')));assert.deepEqual(B.HITS,expected.HITS);assert.deepEqual(B.CHAIN,expected.CHAIN);});
test('Franklin cannot be selected before being unlocked',()=>{const g=new B.Game();g.start(null,'franklin');assert.equal(g.playerKind,'hero');});
test('Franklin becomes playable without replacing the original player',()=>{const g=new B.Game();g.franklinUnlocked=true;g.start(null,'franklin');assert.equal(g.playerKind,'franklin');g.start(null,'hero');assert.equal(g.playerKind,'hero');assert(g.franklinUnlocked);});
test('The final regular wave must be cleared before Franklin appears',()=>{const g=fourth();g.activeGate=2;g.nextGate=2;g.enemies=[];tick(g,100);assert(g.bossSpawned);assert.equal(g.enemies[0].kind,'franklin');assert.equal(g.nextGate,2);assert.equal(g.activeGate,2);assert(!g.bossDefeated);});
test('Living regular enemies prevent an early boss entrance',()=>{const g=fourth();g.spawnFight(2);tick(g,70);assert(!g.bossSpawned);});
test('The boss entrance happens only once, not every empty-frame update',()=>{const g=fourth();g.activeGate=2;g.nextGate=2;g.enemies=[];tick(g,130);assert.equal(g.enemies.filter(e=>e.kind==='franklin').length,1);const id=g.enemies[0].id;tick(g,100);assert.equal(g.enemies[0].id,id);});
test('Stage 4 cannot complete or unlock Franklin by walking past an undefeated boss',()=>{const g=fourth();g.advanceStage();assert.equal(g.mode,'play');assert(!g.franklinUnlocked);});
test('Boss defeat alone does not award the playable character before the exit',()=>{const g=fourth();g.activeGate=2;g.spawnFranklin();g.registerHit(g.enemies[0],{damage:999,kb:0});assert(g.bossDefeated);assert(!g.franklinUnlocked);assert.equal(g.mode,'play');});
test('Death-free Stage 4 plus boss defeat and exit awards Franklin exactly once',()=>{const g=fourth();beatBoss(g);assert.equal(g.mode,'stageclear');assert(g.franklinUnlocked);assert(g.lastUnlockEarned);assert.equal(g.drain().filter(e=>e.type==='unlock').length,1);g.advanceStage();assert.equal(g.drain().filter(e=>e.type==='unlock').length,0);});
test('Deaths in Stages 1-3 do not disqualify a death-free fourth stage',()=>{const g=fourth();g.deathsByStage=[2,1,3,0];beatBoss(g);assert(g.franklinUnlocked);});
test('One Stage 4 death disqualifies the run even when Franklin is defeated',()=>{const g=fourth();g.recordDeath();beatBoss(g);assert.equal(g.mode,'stageclear');assert(!g.franklinUnlocked);assert.equal(g.deathsByStage[3],1);});
test('Death is counted once across the entire death animation',()=>{const g=fourth();g.p.hp=0;tick(g,100);assert.equal(g.deathsByStage[3],1);});
test('Death disqualification is written immediately to the last checkpoint',()=>{const g=fourth();g.p.hp=0;g.step(1/120);const saves=g.drain().filter(e=>e.type==='save');assert(saves.length);assert.equal(saves.at(-1).save.deathsByStage[3],1);assert.equal(saves.at(-1).save.stage4Eligible,false);assert.equal(saves.at(-1).save.nextGate,0);});
test('Checkpoint retry with replenished lives does not erase Stage 4 deaths',()=>{const g=fourth();g.recordDeath();g.retry(true);assert.equal(g.deathsByStage[3],1);assert(!g.stage4Eligible);});
test('Reloading a serialized failed checkpoint does not erase disqualification',()=>{const g=fourth();g.recordDeath();const s=JSON.parse(JSON.stringify(g.checkpoint));const h=new B.Game();h.start(s);assert.equal(h.deathsByStage[3],1);assert(!h.stage4Eligible);});
test('Restart Stage 4 offers a fresh legitimate unlock attempt from its beginning',()=>{const g=fourth();g.recordDeath();assert(g.restartStage4());assert.equal(g.stage,3);assert.equal(g.nextGate,0);assert.equal(g.p.x,170);assert.equal(g.deathsByStage[3],0);assert(g.stage4Eligible);assert(!g.bossSpawned);assert(!g.bossDefeated);beatBoss(g);assert(g.franklinUnlocked);});
test('Already-unlocked Franklin survives failed replays and New Game',()=>{const g=fourth();g.franklinUnlocked=true;g.start(null,'franklin');g.stage=3;g.recordDeath();g.retry(true);assert(g.franklinUnlocked);assert.equal(g.playerKind,'franklin');});
test('Old v2 Stage 4 clear checkpoints cannot skip the newly added boss',()=>{const g=new B.Game();g.start({version:2,stage:3,nextGate:3,lives:2});assert.equal(g.nextGate,2);assert(!g.bossDefeated);assert(!g.stage4Eligible);});
test('Old v2 checkpoints before Stage 4 retain progress and qualify after entering Stage 4',()=>{const g=new B.Game();g.start({version:2,stage:2,nextGate:2,lives:2,score:333});assert.equal(g.stage,2);assert.equal(g.nextGate,2);assert.equal(g.score,333);g.advanceStage();assert.equal(g.mode,'stageclear');g.finishStageClear();assert.equal(g.stage,3);assert(g.stage4Eligible);});
test('Franklin uses the unchanged four-link attack and air-kick input paths',()=>{const g=new B.Game();g.franklinUnlocked=true;g.start(null,'franklin');g.nextGate=3;g.p.x=500;g.step(1/120,{attackPressed:true,attackHeld:true});const seen=[];for(let i=0;i<240;i++){let n=g.p.action?.name;if(n&&seen.at(-1)!==n)seen.push(n);g.step(1/120,{attackHeld:true});}assert.deepEqual(seen,['jab','cross','kick','palm']);g.step(1/120,{jumpPressed:true});tick(g,15);g.step(1/120,{attackPressed:true});assert.equal(g.p.action.name,'air');});
test('Every Franklin mapping resolves to an actual new animation without falling back to the old Elder',()=>{const m=JSON.parse(fs.readFileSync(path.join(__dirname,'../assets/sprites.json')));const names=new Set(Object.keys(m.characters.hero));for(const n of names){if(['belly-bash'].includes(n))continue;const mapped=B.playerAnimation('franklin',n);if(n==='jump'||Object.values(B.HITS).some(x=>x.anim===n)||['idle','walk','run','rise','apex','fall','death','hurt','land','guard','guard-enter','duck'].includes(n))assert(m.characters.franklin[mapped],n+' => '+mapped);}assert(!m.characters.elder);});
test('Boss attacks telegraph before damage and expose recovery',()=>{const g=fourth();g.spawnFranklin();const e=g.enemies[0];e.state='seek';e.x=g.p.x+80;e.y=g.p.y;e.cooldown=0;g.updateFranklin(e,1/120);assert.equal(e.state,'windup');const hp=g.p.hp;for(let i=0;i<50;i++)g.updateFranklin(e,1/120);assert.equal(g.p.hp,hp);for(let i=0;i<180;i++)g.updateFranklin(e,1/120);assert(g.p.hp<hp);assert(['recover','seek'].includes(e.state));});
test('Boss has five distinct source-derived physical attacks',()=>{assert.equal(B.BOSS_MOVES.length,5);assert.equal(new Set(B.BOSS_MOVES.map(m=>m.anim)).size,5);for(const m of B.BOSS_MOVES){assert(m.wind>=.5);assert(m.hits.every(t=>t<m.duration));}});
fs.writeFileSync(path.join(__dirname,'franklin-results.json'),JSON.stringify({tests:results,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length},null,2));if(results.some(r=>!r.passed))process.exitCode=1;
