'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),B=require('../engine.js');const results=[];
function test(name,fn){try{const details=fn();results.push({name,passed:true,details});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:String(e.stack)});console.log('FAIL',name,e.message);}}
function tick(g,n,input={}){for(let i=0;i<n;i++)g.step(1/120,input);}
function arena(){const g=new B.Game();g.start();g.nextGate=3;g.activeGate=-1;g.p.x=600;g.p.y=400;g.enemies=[];g.events=[];return g;}
test('Lethal airborne states continue gravity to the pavement',()=>{for(const [z,v] of [[25,-180],[96,0],[15,350]]){const g=arena();g.p.hp=0;g.p.z=z;g.p.vz=v;tick(g,120);assert.equal(g.p.z,0);assert.equal(g.p.vz,0);assert.equal(g.deathsByStage[0],1);assert(g.p.deadT>0);}});
test('A fatal fall does not teleport straight to ground on the first tick',()=>{const g=arena();g.p.hp=0;g.p.z=65;g.p.vz=-20;g.step(1/120);assert(g.p.z>60&&g.p.z<65);});
test('The clear screen freezes combat and preserves outgoing stage',()=>{const g=arena();g.stage=1;g.p.x=2800;g.advanceStage();assert.equal(g.mode,'stageclear');assert.equal(g.stage,1);const t=g.t;tick(g,200,{attackPressed:true,mx:1});assert.equal(g.t,t);assert.equal(g.p.action,null);});
test('Continue completes the district transition exactly once',()=>{const g=arena();g.p.hp=60;g.p.lives=2;g.advanceStage();assert(g.finishStageClear());assert.equal(g.stage,1);assert.equal(g.p.hp,85);assert.equal(g.p.lives,2);assert(!g.finishStageClear());assert.equal(g.stage,1);});
test('Wave spawn composition remains 39 regular enemies, 29 Shermometers',()=>{const a=B.STAGES.slice(0,4).flatMap(s=>s.waves.flat());assert.equal(a.length,39);assert.equal(a.filter(x=>x.startsWith('sherm')).length,29);});
test('Ordinary arrivals start outside the actual viewport for narrow and wide views',()=>{for(const width of [760,1200,1800]){const g=arena();g.viewWidth=width;g.camera=190;g.stage=2;g.spawnFight(1);for(const e of g.enemies){assert(e.hidden);g.updateEntry(e,.7);assert(e.x<g.camera||e.x>g.camera+width);assert.equal(e.state,'entry');assert.equal(e.anim,'walk');}}});
test('Hidden arrivals cannot be hit or clear their encounter prematurely',()=>{const g=arena();g.spawnFight(0);const e=g.enemies[1];e.x=g.p.x+30;e.y=g.p.y;const hp=e.hp;g.setAction('jab');g.hitTest(B.HITS.jab,g.p.action);assert.equal(e.hp,hp);g.enemies[0].hp=0;tick(g,80);assert.equal(g.activeGate,0);});
test('Sewer emergence is shared by all variants without new damage mechanics',()=>{const g=arena();for(const k of ['sherm-punch','sherm-shove','sherm-slam']){g.stage=0;g.activeGate=0;const e={kind:k,speed:100,y:400,hp:50,cooldown:.3};g.setupEntry(e,0,1);assert.equal(e.entry.route,'sewer');g.updateEntry(e,.1);assert(e.entryDepth>100);assert(!e.targetable);for(let i=0;i<160;i++)g.updateEntry(e,1/120);assert.equal(e.state,'seek');assert.equal(e.entryDepth,0);assert.equal(g.p.hp,100);}});
test('Every ordinary entrant finishes its entry in a bounded interval',()=>{const g=arena();g.stage=0;g.viewWidth=1500;g.p.x=2200;g.camera=1500;g.spawnFight(2);for(let i=0;i<1300;i++)for(const e of g.enemies){e.animT+=1/120;if(e.entry)g.updateEntry(e,1/120);}assert(g.enemies.every(e=>!e.entry&&e.state==='seek'));});
test('Franklin boss arrives physically before the taunt and combat',()=>{const g=arena();g.stage=3;g.activeGate=2;g.spawnFranklin();const e=g.enemies[0];assert(e.hidden&&e.entry.route==='walk');g.updateEntry(e,.01);assert(e.x>g.camera+g.viewWidth);for(let i=0;i<1200&&e.entry;i++)g.updateEntry(e,1/120);assert.equal(e.state,'seek');assert(g.drain().some(e=>e.type==='bossEnter'&&e.kind==='franklin'));});
test('Franklin player receives the existing Slam Shermometer instead of himself',()=>{const g=arena();g.franklinUnlocked=true;g.playerKind='franklin';g.stage=3;g.activeGate=2;g.spawnFranklin();assert.equal(g.enemies[0].kind,'sherm-slam');assert(g.enemies[0].boss);});
test('Alternate boss defeat completes the run without a second unlock award',()=>{const g=arena();g.franklinUnlocked=true;g.playerKind='franklin';g.stage=3;g.activeGate=2;g.spawnFranklin();g.registerHit(g.enemies[0],{damage:999,kb:10});assert(g.bossDefeated);g.advanceStage();assert.equal(g.mode,'stageclear');assert(!g.lastUnlockEarned);assert.equal(g.drain().filter(e=>e.type==='unlock').length,0);});
test('Selected-player route survives serialized Continue and checkpoint retry',()=>{const g=arena();g.franklinUnlocked=true;g.start(null,'franklin');g.stage=3;g.checkpointSave();const save=JSON.parse(JSON.stringify(g.snapshot()));const h=arena();h.franklinUnlocked=true;h.start(save);assert.equal(h.playerKind,'franklin');h.retry(true);h.spawnFranklin();assert.equal(h.enemies[0].kind,'sherm-slam');});
test('Jump/air art changes do not change HITS constants or analog input class',()=>{const base=JSON.parse(fs.readFileSync(path.join(__dirname,'v2-combat-baseline.json')));assert.deepEqual(B.HITS,base.HITS);assert.equal(B.playerAnimation('hero','held-front-kick'),'air-kick-v4');assert.equal(B.playerAnimation('hero','apex'),'apex-v4');assert.equal(B.playerAnimation('franklin','held-front-kick'),'held-front-kick');});
test('Franklin route remains completable using normal combat inputs',()=>{const g=new B.Game();g.franklinUnlocked=true;g.start(null,'franklin');let ticks=0,retries=0,stages=new Set();for(;ticks<120*1500&&g.mode!=='complete';ticks++){if(g.mode==='confrontation')g.finishDukeConfrontation();if(g.mode==='gameover'){retries++;g.retry(true);}if(g.mode==='stageclear')g.finishStageClear();if(g.mode!=='play')continue;stages.add(g.stage);const p=g.p,live=g.enemies.filter(e=>e.hp>0).concat(g.props.filter(o=>o.kind==='circuit'&&o.hp>0)).sort((a,b)=>Math.hypot(a.x-p.x,(a.y-p.y)*2)-Math.hypot(b.x-p.x,(b.y-p.y)*2));let i={};if(live.length){const e=live[0],dx=e.x-p.x,dy=e.y-p.y;i.mx=Math.abs(dx)>62?Math.sign(dx)*(Math.abs(dx)>150?1:.4):0;i.my=Math.abs(dy)>8?Math.sign(dy)*.55:0;i.attackPressed=Math.abs(dx)<122&&Math.abs(dy)<25&&ticks%12===0;i.attackHeld=Math.abs(dx)<116&&Math.abs(dy)<27;if(p.meter>=100&&live.length>1&&!p.action)i.specialPressed=true;}else i.mx=1;g.step(1/120,i);g.drain();}assert.equal(g.mode,'complete');assert.equal(stages.size,7);assert(g.bossDefeated);return {seconds:g.t,retries,kos:g.stats.kos};});
fs.writeFileSync(path.join(__dirname,'v4-engine-results.json'),JSON.stringify({tests:results,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length},null,2));if(results.some(x=>!x.passed))process.exitCode=1;
