'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),B=require('../engine.js');const results=[];
function test(name,fn){try{results.push({name,passed:true,details:fn()});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:String(e.stack)});console.error('FAIL',name,e.message);}}
function tick(g,n,input={}){for(let i=0;i<n;i++)g.step(1/120,typeof input==='function'?input(i):input);}
function arena(character='hero',stage=0){const g=new B.Game();g.franklinUnlocked=character==='franklin';g.start(null,character);g.stage=stage;g.nextGate=3;g.activeGate=-1;g.props=[];g.enemies=[];g.p.x=600;g.p.y=407;g.events=[];return g;}
function foe(g,x=g.p.x+70,y=g.p.y){const e={id:++g.enemyId,kind:'sherm-punch',name:'Shermometer v1',elite:false,x,y,z:0,face:-1,hp:999,maxHp:999,speed:0,state:'seek',timer:0,cooldown:999,anim:'idle',animT:0,animDuration:0,kb:0,variant:0,flashes:0};g.enemies.push(e);return e;}
function machine(character='hero'){const g=arena(character,6);g.activeGate=g.nextGate=2;g.p.x=2240;g.spawnBoss();return g;}
function defeatMachine(g){require('./v9-fixtures').defeatMachine(g);}
test('All accepted normal, air, guard-counter and Review hit definitions remain unchanged',()=>{const base=JSON.parse(fs.readFileSync(path.join(__dirname,'v2-combat-baseline.json')));assert.deepStrictEqual(B.HITS,base.HITS);assert.deepStrictEqual(B.CHAIN,base.CHAIN);});
test('Running moves preserve damage and lane reach with deliberate Franklin retiming',()=>{for(const kind of ['hero','franklin']){const s=B.RUN_ATTACKS[kind];for(const field of ['damage','range'])assert.equal(s[field],B.HITS.dash[field]);assert.equal(s.dur,kind==='hero'?.43:.56);assert.equal(s.hit,kind==='hero'?.18:.24);assert.equal(s.end,s.dur);assert(s.launch>0&&s.launch<.5);}assert.equal(B.RUN_ATTACKS.hero.anim,'belly-bash');assert.equal(B.RUN_ATTACKS.franklin.anim,'cartwheel-run');assert.equal(B.HITS.dash.anim,'attack');});
test('Jay and Franklin use their own run attack, hit once, and launch lane-valid foes visibly',()=>{
 const reports=[];for(const character of ['hero','franklin']){const g=arena(character);tick(g,40,{mx:1});const before=g.p.x,good=foe(g,g.p.x+125),other=foe(g,g.p.x+125,g.p.y+49),origin=good.x;g.step(1/120,{mx:1,attackPressed:true});assert.equal(g.p.action.name,'charge');tick(g,25,{mx:1});assert.equal(g.p.action.name,'dash');assert.equal(g.p.anim,B.RUN_ATTACKS[character].anim);tick(g,100);assert.equal(999-good.hp,24);assert.equal(other.hp,999);assert.equal(g.stats.hits,1);assert(good.x-origin>290&&good.x-origin<330);assert.equal(good.launchTimer,0);assert(g.hitstop<=.075);assert.equal(g.p.action,null);reports.push({character,animation:B.RUN_ATTACKS[character].anim,launchTravel:good.x-origin,playerTravel:g.p.x-before});}return reports;
});
test('Run attack strongest source contact is retimed to its existing active hit',()=>{for(const character of ['hero','franklin']){const g=arena(character);g.setAction('dash');g.p.action.t=B.RUN_ATTACKS[character].hit;g.chooseAnimation(0,0);assert.equal(g.p.anim,B.RUN_ATTACKS[character].anim);assert(Math.abs(g.p.animT/g.p.animDuration-B.RUN_ATTACKS[character].sourceImpact)<1e-9);}});
test('Jay Belly Bash never becomes Franklin’s running performance',()=>{const g=arena('franklin');g.setAction('dash');g.chooseAnimation(0,0);assert.equal(g.p.anim,'cartwheel-run');assert.notEqual(g.p.anim,'belly-bash');});
test('Machine defeat holds the arena for Duke and cannot rescue Marty or reach results',()=>{const g=machine();defeatMachine(g);assert.equal(g.mode,'confrontation');assert.equal(g.finalPhase,'duke');assert(g.machineDefeated);assert(!g.dukeDefeated);assert(!g.bossDefeated);assert(!g.storyFlags.martyRescued);g.advanceStage();assert.equal(g.mode,'confrontation');const story=g.drain().filter(e=>e.type==='story').map(e=>e.id);assert(story.includes('boss-broadcast-intro'));assert(story.includes('boss-broadcast-defeat'));assert(!story.includes('boss-duke-defeat'));const t=g.t;tick(g,100,{attackPressed:true,mx:1});assert.equal(g.t,t);});
test('Scene completion or skip creates one real grounded Duke boss and one introduction',()=>{for(const skipped of [false,true]){const g=machine();defeatMachine(g);g.drain();assert(g.finishDukeConfrontation());assert(!g.finishDukeConfrontation());assert.equal(g.mode,'play');assert.equal(g.enemies.length,1);const e=g.enemies[0];assert.equal(e.kind,'duke');assert.equal(e.entry.route,'stairs');for(let i=0;i<300&&e.entry;i++)g.updateEntry(e,1/120);assert.equal(e.z,0);assert(e.y>=B.YMIN&&e.y<=B.YMAX);assert.equal(e.state,'seek');assert.equal(g.drain().filter(e=>e.type==='story'&&e.id==='boss-duke-intro').length,1);g.storyCompleted('boss-broadcast-defeat');assert.equal(skipped?g.storyFlags['boss-broadcast-defeat']:g.storyFlags['boss-broadcast-defeat'],true);}});
test('Duke’s seven attacks have source-backed physical motion, telegraphs and recovery',()=>{const sprites=JSON.parse(fs.readFileSync(path.join(__dirname,'../assets/sprites.json')));const def=B.BOSS_DEFINITIONS.duke;assert.equal(def.moves.length,7);assert.equal(new Set(def.moves.map(m=>m.name)).size,7);for(const move of def.moves){assert(sprites.characters.duke[move.anim]);assert(sprites.characters.duke[move.windAnim||'idle']);assert(move.wind>=.6);assert(move.hits.every(t=>t<move.duration));assert((move.recovery||def.recovery)>=.7);assert(!move.area);}assert(def.moves.some(m=>m.rush));});
test('Actual Duke telegraphs, strikes and exposes recovery',()=>{const g=machine();defeatMachine(g);g.finishDukeConfrontation();const e=g.enemies[0];e.entry=null;e.hidden=false;e.targetable=true;e.state='seek';e.x=g.p.x+80;e.y=g.p.y;e.cooldown=0;g.updateBoss(e,1/120);assert.equal(e.state,'windup');const hp=g.p.hp;g.updateBoss(e,e.move.wind-.02);assert.equal(g.p.hp,hp);g.updateBoss(e,.03);for(let i=0;i<240&&e.state==='attack';i++)g.updateBoss(e,1/120);assert.equal(e.state,'recover');assert(g.p.hp<hp);});
test('Duke defeat gates Marty rescue and the final ending for both routes',()=>{for(const character of ['hero','franklin']){const g=machine(character);defeatMachine(g);g.finishDukeConfrontation();g.drain();g.advanceStage();assert.equal(g.mode,'play');assert(!g.storyFlags.martyRescued);const e=g.enemies[0];g.registerHit(e,{damage:9999,kb:0});assert(g.dukeDefeated);assert.equal(g.finalPhase,'resolved');assert(!g.storyFlags.martyRescued);const score=g.score;assert.equal(g.registerHit(e,{damage:9999,kb:0}),false);assert.equal(g.score,score);tick(g,500);g.nextGate=3;g.activeGate=-1;g.advanceStage();assert.equal(g.mode,'complete');assert(g.storyFlags.martyRescued&&g.storyFlags.broadcastStopped);assert.equal(g.drain().filter(e=>e.type==='complete'&&e.boss==='duke').length,1);assert(!g.finishDukeConfrontation());}});
test('New machine-defeat save resumes only Duke without replaying waves or the machine',()=>{const g=machine();defeatMachine(g);const s=JSON.parse(JSON.stringify(g.snapshot()));assert.equal(s.version,5);assert.equal(s.buildVersion,11);const h=new B.Game();h.start(s);assert.equal(h.stage,6);assert.equal(h.activeGate,2);assert.equal(h.finalPhase,'duke');assert.equal(h.enemies.length,1);assert.equal(h.enemies[0].kind,'duke');assert.equal(h.score,g.score);assert(!h.dukeDefeated&&!h.storyFlags.martyRescued);assert.equal(h.drain().filter(e=>e.type==='story'&&e.id==='boss-duke-intro').length,0);});
test('Old v4 completed transmitter saves migrate to the new required Duke confrontation',()=>{const g=new B.Game();g.start({version:4,stage:6,nextGate:3,bossDefeated:true,complete:true,score:5432,franklinUnlocked:true,playerKind:'franklin',storyFlags:{martyRescued:true,ending:true}});assert.equal(g.finalPhase,'duke');assert.equal(g.playerKind,'franklin');assert(g.franklinUnlocked);assert.equal(g.score,5432);assert.equal(g.enemies[0].kind,'duke');assert(!g.storyFlags.martyRescued&&!g.dukeDefeated);});
test('Duke-death checkpoint reload preserves defeat and never duplicates his boss',()=>{const g=machine();defeatMachine(g);g.finishDukeConfrontation();g.registerHit(g.enemies[0],{damage:9999,kb:0});const h=new B.Game();h.start(g.snapshot());assert.equal(h.finalPhase,'resolved');assert(h.dukeDefeated);assert.equal(h.nextGate,3);assert.equal(h.enemies.length,0);assert(!h.finishDukeConfrontation());h.advanceStage();assert.equal(h.mode,'complete');});
test('One temporary remote carries its stable circuit color without permanent floor targets',()=>{const g=arena('hero',4);g.activeGate=2;g.camera=1820;g.p.x=2200;g.configureProjection();g.spawnBoothCircuits();assert.equal(g.props.length,0);for(let id=0;id<3;id++){assert(g.dropRemote(id));const o=g.props.find(o=>o.hp>0);assert.equal(o.color,g.projection.circuits[id].color);assert.equal(o.circuitId,id);assert(!g.dropRemote(id));g.disableCircuit(id);}assert(g.projection.disabled);});
test('Projectionist is visibly revealed before locking a target or launching a reel',()=>{const g=arena('hero',4);g.activeGate=2;g.camera=1820;g.p.x=2200;g.configureProjection();g.updateProjection(2.41);assert.equal(g.projection.phase,'shadow');assert(g.projection.visible);assert.equal(g.projection.window,0);assert.equal(g.projection.telegraph,null);assert.equal(g.projectiles.length,0);g.updateProjection(1.16);assert.equal(g.projection.phase,'reveal');g.updateProjection(.54);assert.equal(g.projection.phase,'reveal');g.updateProjection(.02);assert.equal(g.projection.phase,'telegraph');const target={...g.projection.telegraph};g.p.y+=45;g.updateProjection(1.14);assert.equal(g.projectiles.length,0);g.updateProjection(.02);assert.equal(g.projectiles.length,1);assert(g.projection.visible);assert.equal(g.projectiles[0].targetY,target.y);assert.equal(g.projectiles[0].circuitId,0);g.updateProjectiles(.71);assert.equal(g.p.hp,100);});
test('Breaking one circuit powers down only its matching window and cancels only its reels',()=>{const g=arena('hero',4);g.activeGate=2;g.camera=1820;g.p.x=2200;g.configureProjection();g.spawnBoothCircuits();g.projection.window=1;g.projection.visible=true;g.projection.phase='throw';g.launchProjectile('reel',2310,g.projection.windowY,g.p.x,g.p.y,9,32,.7,1);g.launchProjectile('reel',2530,g.projection.windowY,g.p.x,g.p.y,9,32,.7,2);assert(g.disableCircuit(1));assert(!g.projection.circuits[1].active);assert(g.projection.circuits[0].active&&g.projection.circuits[2].active);assert.equal(g.projectiles.length,1);assert.equal(g.projectiles[0].circuitId,2);assert(!g.projection.visible);g.updateProjection(2.41);assert.equal(g.projection.booths[g.projection.window].circuitId,0);assert(g.projection.visible);assert(!g.disableCircuit(1));assert.equal(g.drain().filter(e=>e.type==='circuitDisabled'&&e.circuitId===1).length,1);});
test('Partial circuits survive Continue without recreating retired boxes',()=>{const g=arena('hero',4);g.activeGate=g.nextGate=2;g.configureProjection();g.disableCircuit(0);const h=new B.Game();h.start(g.snapshot());h.spawnFight(2);assert(!h.projection.circuits[0].active);assert(!h.props.some(o=>o.kind==='circuit'));assert.equal(h.projection.circuits.filter(c=>c.active).length,2);const old=new B.Game();old.start({version:4,stage:4,nextGate:2});assert.deepStrictEqual(old.projection.circuits.map(c=>c.active),[true,true,true]);});
test('Complete circuit shutdown is idempotent, ends attacks and updates the objective once',()=>{const g=arena('hero',4);g.activeGate=2;g.camera=1820;g.p.x=2200;g.configureProjection();g.spawnBoothCircuits();for(let i=0;i<3;i++)g.disableCircuit(i);assert(g.projection.disabled);assert.equal(g.projection.circuits.filter(c=>c.active).length,0);assert(!g.projection.active&&!g.projection.visible);assert.equal(g.projectiles.length,0);assert(!g.disableCircuit(2));assert.equal(g.drain().filter(e=>e.type==='story'&&e.id==='boss-projection-defeat').length,1);});
test('Spike emerges from an explicit pizzeria door and uses one fixed body scale',()=>{const g=arena('hero',5);g.activeGate=2;g.spawnBoss();const e=g.enemies[0];assert.equal(e.kind,'spike');assert.equal(e.renderScale,1.08);assert.equal(e.entry.route,'door');assert.equal(e.entry.sourceX,2630);g.updateEntry(e,.01);assert.equal(e.entry.phase,'door-open');assert(!e.hidden&&!e.targetable);assert.equal(e.x,2630);g.updateEntry(e,.4);assert.equal(e.entry.phase,'walk');assert.equal(g.drain().filter(x=>x.type==='bossEntrance'&&x.source==='pizzeria-door').length,1);});
test('Street props have one consistent larger presentation scale without changed break/drop values',()=>{for(const stage of [0,4,6]){const g=arena('hero',stage);g.resetWorld();assert(g.props.every(p=>p.scale===1.35));assert.equal(g.props[0].hp,20);assert.equal(g.props[1].hp,24);assert.equal(g.props[2].hp,20);}assert.equal(B.ITEMS.coffee.health,18);});
fs.writeFileSync(path.join(__dirname,'v7-engine-results.json'),JSON.stringify({tests:results,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length},null,2));if(results.some(r=>!r.passed))process.exitCode=1;
