'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),B=require('../engine.js');const results=[];
function test(name,fn){try{results.push({name,passed:true,details:fn()});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:String(e.stack)});console.error('FAIL',name,e.message);}}
function tick(g,n,input={}){for(let i=0;i<n;i++)g.step(1/120,typeof input==='function'?input(i):input);}
function arena(character='hero',stage=0){const g=new B.Game();g.franklinUnlocked=character==='franklin';g.start(null,character);g.stage=stage;g.nextGate=3;g.activeGate=-1;g.props=[];g.enemies=[];g.p.x=600;g.p.y=407;g.camera=0;g.events=[];return g;}
function foe(g,kind='sherm-punch',x=g.p.x+70,y=g.p.y){const k=B.EINFO[kind],e={id:++g.enemyId,kind,name:k.name,elite:false,x,y,z:0,face:-1,hp:999,maxHp:999,speed:0,state:'seek',timer:0,cooldown:999,anim:'idle',animT:0,animDuration:0,kb:0,variant:0,flashes:0};g.enemies.push(e);return e;}
function machine(character='hero'){const g=arena(character,6);g.activeGate=g.nextGate=2;g.p.x=2240;g.camera=1820;g.spawnBoss();return g;}
function cinema(){const g=arena('hero',4);g.activeGate=g.nextGate=2;g.p.x=2180;g.camera=1820;g.configureProjection();return g;}
function clearEntry(e){e.entry=null;e.hidden=false;e.targetable=true;e.state='seek';e.timer=e.animT=0;e.cooldown=0;}
test('The accepted four-link combo, air, guard-counter and Review constants remain exact',()=>{const base=JSON.parse(fs.readFileSync(path.join(__dirname,'v2-combat-baseline.json')));assert.deepStrictEqual(B.HITS,base.HITS);assert.deepStrictEqual(B.CHAIN,base.CHAIN);});
test('Jay retains Belly Bash while Franklin uses the supplied 26-pose cartwheel contact',()=>{const sprites=JSON.parse(fs.readFileSync(path.join(__dirname,'../assets/sprites.json')));assert.equal(B.RUN_ATTACKS.hero.anim,'belly-bash');assert.equal(B.RUN_ATTACKS.franklin.anim,'cartwheel-run');assert.equal(B.RUN_ATTACKS.franklin.sourceImpact,11/26);assert.equal(sprites.characters.franklin['cartwheel-run'].frames.length,26);for(const kind of ['hero','franklin']){const g=arena(kind);g.setAction('dash');g.p.action.t=B.HITS.dash.hit;g.chooseAnimation(0,0);assert.equal(g.p.anim,B.RUN_ATTACKS[kind].anim);assert(Math.abs(g.p.animT/g.p.animDuration-B.RUN_ATTACKS[kind].sourceImpact)<1e-12);}});
test('Run collision with Bear or Hippo resists damage and launch on both playable routes',()=>{for(const kind of ['hero','franklin'])for(const heavy of ['bear','hippo']){const g=arena(kind),e=foe(g,heavy);g.p.face=1;g.p.combo=7;g.p.chainIndex=3;g.p.counter=.5;g.p.attackBuffer=.2;g.p.jumpBuffer=.1;g.setAction('dash');g.hitTest(g.attackSpec('dash'),g.p.action);assert.equal(e.hp,999);assert.equal(e.kb,0);assert.equal(e.launchTimer,undefined);assert.equal(g.p.action.name,'run-stun');assert.equal(g.p.action.dur,.6);assert.equal(g.p.vx,-130);for(const key of ['combo','comboClock','chainIndex','counter','attackBuffer','jumpBuffer'])assert.equal(g.p[key],0);assert.equal(g.stats.hits,0);assert.equal(g.drain().filter(e=>e.type==='runBlocked').length,1);}});
test('A heavy blocker wins nearest-front ordering for either facing regardless of array order',()=>{for(const face of [-1,1])for(const heavyFirst of [true,false]){const g=arena(),heavy=foe(g,'bear',g.p.x+face*50),behind=foe(g,'sherm-punch',g.p.x+face*90);g.enemies=heavyFirst?[heavy,behind]:[behind,heavy];g.p.face=face;g.setAction('dash');g.hitTest(g.attackSpec('dash'),g.p.action);assert.equal(heavy.hp,999);assert.equal(behind.hp,999);assert.equal(g.p.action.name,'run-stun');}});
test('An out-of-lane heavy enemy never blocks a valid running hit',()=>{const g=arena(),heavy=foe(g,'hippo',g.p.x+40,g.p.y+45),normal=foe(g,'sherm-punch',g.p.x+80);g.p.face=1;g.setAction('dash');g.hitTest(g.attackSpec('dash'),g.p.action);assert.equal(heavy.hp,999);assert.equal(normal.hp,975);assert.equal(g.p.action.name,'dash');assert(normal.launchTimer>0);});
test('Standing combos still damage Bear and Hippo with the original hit values',()=>{for(const kind of ['bear','hippo']){const g=arena(),e=foe(g,kind);g.p.face=1;g.setAction('jab');g.hitTest(B.HITS.jab,g.p.action);assert.equal(e.hp,989);assert.equal(g.p.combo,1);assert.equal(g.p.action.name,'jab');}});
test('Repeated collision frames emit one stun and cannot resume a buffered old combo',()=>{const g=arena(),e=foe(g,'bear');g.p.face=1;g.setAction('dash');g.p.action.t=.18;g.updateAction(1/120,{});assert.equal(g.p.action.name,'run-stun');tick(g,65,{attackHeld:true,attackPressed:true});assert.equal(g.p.action.name,'run-stun');assert.equal(e.hp,999);assert.equal(g.p.attackBuffer,0);tick(g,20);assert.equal(g.p.action,null);assert.equal(g.drain().filter(e=>e.type==='runBlocked').length,1);});
test('Violent Austrian Rabbi replaces the booth enforcer; Spike occupies Little Italy',()=>{assert.equal(B.STAGES[4].boss.kind,'pizzeria-boss');assert.equal(B.STAGES[4].boss.intro,'boss-cinema-intro');assert.equal(B.EINFO['pizzeria-boss'].name,'Violent Austrian Rabbi');assert.equal(B.EINFO['pizzeria-boss'].renderScale,1.24);assert.equal(B.STAGES[5].boss.kind,'spike');assert.equal(B.STAGES[5].boss.hp,340);assert.equal(B.EINFO.spike.speed,115);assert.equal(B.EINFO.spike.renderScale,1.08);});
test('The Violent Austrian Rabbi visibly emerges from the film screen before fighting',()=>{const g=cinema();g.spawnBoss();const e=g.enemies[0];assert.equal(e.entry.route,'screen');assert.equal(e.entry.sourceX,2450);assert.equal(e.entry.sourceY,316);g.updateEntry(e,.01);assert.equal(e.entry.phase,'emerge');assert(!e.hidden&&!e.targetable);assert(e.entryScale<=.3);for(let i=0;i<400&&e.entry;i++)g.updateEntry(e,1/120);assert.equal(e.entry,null);assert.equal(e.entryScale,1);assert.equal(e.y,409);assert.equal(e.state,'seek');assert.equal(g.drain().filter(e=>e.type==='bossEntrance'&&e.source==='cinema-screen').length,1);});
test('Cinema completion requires both the headliner defeat and all three circuits',()=>{for(const circuitsFirst of [true,false]){const g=cinema();g.spawnBoss();const boss=g.enemies[0];if(circuitsFirst){for(let i=0;i<3;i++)g.disableCircuit(i);g.advanceStage();assert.equal(g.mode,'play');g.registerHit(boss,{damage:9999,kb:0});}else{g.registerHit(boss,{damage:9999,kb:0});g.advanceStage();assert.equal(g.mode,'play');for(let i=0;i<3;i++)g.disableCircuit(i);}g.advanceStage();assert.equal(g.mode,'stageclear');assert.equal(g.drain().filter(e=>e.type==='story'&&e.id==='boss-cinema-defeat').length,1);}});
test('Booths extend over the full wall with three fixed world-space circuit groups',()=>{const g=cinema();assert.deepStrictEqual(g.projection.windowXs,[170,390,610,830,1050,1270,1490,1710,1930,2110,2310,2530,2750]);assert.equal(g.projection.booths.length,13);for(const b of g.projection.booths){assert.equal(b.x,g.projection.windowXs[b.id]);assert.equal(b.circuitId,b.id%3);}g.spawnBoothCircuits();for(const c of g.props){assert.equal(g.projection.booths[c.window].circuitId,c.circuitId);}});
test('Projectionist appears only in active onscreen booths and choreographs eyes before reveal',()=>{const g=cinema();g.updateProjection(2.41);assert.equal(g.projection.phase,'shadow');assert(g.projection.visible);const b=g.projection.booths[g.projection.window];assert(b.x>=g.camera+70&&b.x<=g.camera+g.viewWidth-70);g.updateProjection(.39);assert.equal(g.projection.phase,'shadow');g.updateProjection(.02);assert.equal(g.projection.phase,'reveal');g.updateProjection(.54);assert.equal(g.projection.phase,'reveal');g.updateProjection(.02);assert.equal(g.projection.phase,'telegraph');assert.equal(g.projectiles.length,0);const target={...g.projection.telegraph};g.p.y+=45;g.updateProjection(1.16);assert.equal(g.projectiles.length,1);assert.equal(g.projectiles[0].targetY,target.y);assert.equal(g.projectiles[0].circuitId,b.circuitId);});
test('Offscreen camera movement cancels the current booth warning before any invisible attack',()=>{const g=cinema();g.updateProjection(2.41);const first=g.projection.window;g.camera=0;g.updateProjection(.01);assert.equal(g.projectiles.length,0);assert.notEqual(g.projection.window,first);const b=g.projection.booths[g.projection.window];assert(b.x>=70&&b.x<=930);assert.equal(g.projection.phase,'shadow');});
test('Circuit shutdown powers down its entire booth group and cancels only matching reels',()=>{const g=cinema();g.spawnBoothCircuits();g.projection.window=10;g.projection.visible=true;g.projection.phase='throw';g.launchProjectile('reel',2310,196,g.p.x,g.p.y,9,32,.7,1);g.launchProjectile('reel',2530,196,g.p.x,g.p.y,9,32,.7,2);g.disableCircuit(1);assert(!g.projection.visible);assert(!g.projection.circuits[1].active);assert(g.visibleBooths().every(b=>b.circuitId!==1));assert.equal(g.projectiles.length,1);assert.equal(g.projectiles[0].circuitId,2);});
test('Reels make three visible forward floor hops before expiring',()=>{const g=cinema();g.p.y=465;const q=g.launchProjectile('reel',2000,196,2200,380);g.updateProjectiles(.7);assert.equal(q.phase,'bounce');assert.equal(q.bounces,0);assert.equal(q.hopTo,2262);g.updateProjectiles(.15);assert(q.z>35);g.updateProjectiles(.15);assert.equal(q.bounces,1);assert.equal(q.x,2262);g.updateProjectiles(.3);assert.equal(q.bounces,2);assert.equal(q.x,2324);g.updateProjectiles(.3);assert.equal(q.bounces,3);assert.equal(q.x,2386);assert.equal(g.projectiles.length,0);assert.equal(g.drain().filter(e=>e.type==='projectileBounce').length,3);});
test('Reel boundary reflections reverse travel without leaving the active combat arena',()=>{const g=cinema();g.p.y=465;const q=g.launchProjectile('reel',2400,196,2760,380);g.updateProjectiles(.7);assert.equal(q.face,-1);assert.equal(q.hopTo,2698);g.updateProjectiles(.9);assert(q.x>=1795&&q.x<=2775);assert.equal(g.projectiles.length,0);});
test('An unblocked reel hits once, knocks down, then recovers without changing ground',()=>{const g=cinema(),y=g.p.y;const q=g.launchProjectile('reel',g.p.x-150,196,g.p.x,g.p.y);g.updateProjectiles(.7);assert.equal(g.p.hp,91);assert.equal(g.p.action.name,'knockdown');assert.equal(g.p.action.dur,.88);g.updateProjectiles(.15);g.p.x=q.x;g.updateProjectiles(.15);assert.equal(g.p.hp,91);assert.equal(g.drain().filter(e=>e.type==='playerKnockdown').length,1);tick(g,120);assert.equal(g.p.action,null);assert.equal(g.p.y,y);assert.equal(g.p.z,0);});
test('Guard and parry use the incoming side after either bounce reflection',()=>{for(const face of [-1,1])for(const parry of [true,false]){const g=cinema();g.p.face=-face;g.p.guard=true;g.p.guardAge=parry?.05:.5;const q=g.launchProjectile('reel',g.p.x-face*200,196,g.p.x-face*30,g.p.y);q.phase='bounce';q.age=0;q.hopFrom=g.p.x-face*30;q.hopTo=g.p.x+face*32;q.face=face;q.z=0;g.updateProjectiles(.08);assert.equal(g.p.hp,100);assert.equal(g.p.action,null);assert(q.contacted);assert.equal(g.drain().filter(e=>e.type===(parry?'parry':'block')).length,1);}});
test('A guard facing away from a reflected reel cannot protect the player',()=>{for(const face of [-1,1]){const g=cinema();g.p.face=face;g.p.guard=true;g.p.guardAge=.5;const q=g.launchProjectile('reel',g.p.x-face*200,196,g.p.x-face*30,g.p.y);q.phase='bounce';q.age=0;q.hopFrom=g.p.x-face*30;q.hopTo=g.p.x+face*32;q.face=face;g.updateProjectiles(.08);assert.equal(g.p.hp,91);assert.equal(g.p.action.name,'knockdown');}});
test('Spike exits the pizzeria door and has two can attacks plus a close-range punch',()=>{const g=arena('hero',5);g.activeGate=2;g.p.x=2240;g.camera=1820;g.spawnBoss();const e=g.enemies[0];assert.equal(e.kind,'spike');assert.equal(e.entry.route,'door');g.updateEntry(e,.01);assert.equal(e.entry.phase,'door-open');assert(!e.targetable);const def=B.BOSS_DEFINITIONS.spike;assert.equal(def.moves.length,3);assert.equal(def.moves.filter(m=>m.area==='trash-can').length,2);assert(def.moves.some(m=>m.name==='BACK OFF'&&!m.area));});
test('Spike locks a fair warning and retimes the can release to the imported handoff pose',()=>{for(const face of [-1,1]){const g=arena('hero',5);g.activeGate=2;g.p.x=2240;g.camera=1820;g.spawnBoss();const e=g.enemies[0];clearEntry(e);e.x=g.p.x-face*300;e.y=g.p.y;e.face=face;g.updateBoss(e,1/120);assert.equal(e.move.name,'CAN TOSS');const target={...e.telegraph},hp=g.p.hp;for(let i=0;i<107;i++)g.updateBoss(e,1/120);assert.equal(g.projectiles.length,0);assert.equal(g.p.hp,hp);g.updateBoss(e,.02);assert.equal(e.state,'attack');g.updateBoss(e,.32);assert.equal(g.projectiles.length,1);const q=g.projectiles[0];assert.equal(q.kind,'trash-can');assert.equal(q.targetX,target.x);assert.equal(q.sourceX,e.x+face*121.8397212543554*e.renderScale);assert.equal(q.sourceY,e.y-126.37630662020906*e.renderScale);assert.equal(e.anim,'trash-throw');assert(Math.abs(e.animT/e.animDuration-7/19)<1e-9);assert.equal(g.p.hp,hp);g.p.y+=45;g.updateProjectiles(q.duration);assert.equal(g.p.hp,hp);}});
test('Spike keeps his release direction aligned with the locked warning when the player crosses behind',()=>{const g=arena('hero',5);g.activeGate=2;g.p.x=2240;g.spawnBoss();const e=g.enemies[0];clearEntry(e);e.x=1940;e.y=g.p.y;g.updateBoss(e,1/120);assert.equal(e.face,1);assert.equal(e.telegraph.x,2240);g.p.x=1830;g.updateBoss(e,.91);assert.equal(e.face,1);g.updateBoss(e,.33);const q=g.projectiles[0];assert.equal(q.targetX,2240);assert.equal(q.sourceX,e.x+121.8397212543554*e.renderScale);assert.equal(q.face,e.face);});
test('Spike’s final 1.08 body scale carries the measured source-can handoff into world coordinates',()=>{const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../production/v8-assets.json'))).projectileSourceCenterAtRelease;for(const face of [-1,1]){const g=arena('hero',5);g.activeGate=2;g.p.x=2240;g.spawnBoss();const e=g.enemies[0];clearEntry(e);e.x=g.p.x-face*300;e.y=g.p.y;g.updateBoss(e,1/120);g.updateBoss(e,.91);g.updateBoss(e,.33);const q=g.projectiles[0],worldX=e.x+face*source.faceRelativeX*e.renderScale,worldY=e.y-source.heightAboveGround*e.renderScale;assert.equal(e.renderScale,1.08);assert.equal(q.renderScale,e.renderScale);assert(Math.abs(q.sourceX-worldX)<.001);assert(Math.abs(q.sourceY-worldY)<.001);assert(Math.abs(Math.abs(q.sourceX-e.x)-131.58689895470386)<.001);assert(Math.abs(e.y-q.sourceY-136.4864111498258)<.001);}});
test('The transmitter sends bounded, repeated Shermometer waves from visible screens',()=>{const g=machine();g.updateBroadcastSummons(1.19);assert.equal(g.enemies.length,1);g.updateBroadcastSummons(.02);assert.equal(g.broadcastSummons.wave,1);assert.equal(g.enemies.filter(e=>e.broadcastSummon&&e.hp>0).length,2);for(const e of g.enemies.filter(e=>e.broadcastSummon)){assert.equal(e.entry.route,'broadcast');assert([2170,2650].includes(e.entry.sourceX));assert.equal(e.entry.sourceY,230);assert(!e.targetable);}g.updateBroadcastSummons(5.01);assert.equal(g.broadcastSummons.wave,2);assert.equal(g.enemies.filter(e=>e.broadcastSummon&&e.hp>0).length,4);g.updateBroadcastSummons(50);assert.equal(g.broadcastSummons.wave,2);for(const e of g.enemies)if(e.broadcastSummon){e.hp=0;e.state='dead';e.timer=2;}g.updateBroadcastSummons(.01);assert.equal(g.broadcastSummons.wave,3);assert.equal(g.enemies.filter(e=>e.broadcastSummon&&e.hp>0).length,2);assert.equal(g.enemies.length,3);});
test('Machine shutdown dismisses surviving summons without free KO rewards or early rescue',()=>{for(const kind of ['hero','franklin']){const g=machine(kind);g.updateBroadcastSummons(1.21);g.launchProjectile('signal',2450,219,g.p.x,g.p.y);const kos=g.stats.kos;g.registerHit(g.enemies.find(e=>e.kind==='broadcast-rig'),{damage:9999,kb:0});assert.equal(g.mode,'confrontation');assert.equal(g.stats.kos,kos+1);assert(!g.broadcastSummons.active);assert(g.enemies.filter(e=>e.broadcastSummon).every(e=>e.hp===0&&e.hidden));assert.equal(g.projectiles.length,0);assert(!g.storyFlags.martyRescued);g.updateBroadcastSummons(99);assert.equal(g.broadcastSummons.wave,1);assert.equal(g.drain().filter(e=>e.type==='summonsDismissed').length,1);assert(g.finishDukeConfrontation());assert.equal(g.enemies[0].kind,'duke');assert.equal(g.enemies.length,1);}});
test('Duke is faster and stronger while keeping three readable physical attacks and recoveries',()=>{assert.equal(B.STAGES[6].finalBoss.hp,340);assert.equal(B.EINFO.duke.speed,145);const def=B.BOSS_DEFINITIONS.duke;assert.equal(def.hurtRecovery,.4);assert.deepStrictEqual(def.moves.map(m=>m.wind),[.6,.7,.8]);assert.deepStrictEqual(def.moves.map(m=>m.damage),[14,19,18]);assert.equal(def.moves[2].rush,215);assert.equal(def.moves.length,3);assert(def.moves.every(m=>(m.recovery||def.recovery)>=.7));assert(def.moves.every(m=>m.hits.every(t=>t<m.duration)));assert(def.moves.every(m=>!m.area));});
test('Schema 5 checkpoints preserve unlocks and resolved boss phases with build version 8',()=>{for(const kind of ['hero','franklin']){const g=machine(kind);g.updateBroadcastSummons(1.21);const snap=g.snapshot();assert.equal(snap.version,5);assert.equal(snap.buildVersion,8);assert(!('broadcastSummons' in snap));const h=new B.Game();h.start(snap);assert.equal(h.playerKind,kind);assert.equal(h.franklinUnlocked,kind==='franklin');assert(!h.broadcastSummons.active);g.registerHit(g.enemies[0],{damage:9999,kb:0});const k=new B.Game();k.start({...g.snapshot(),buildVersion:7});assert.equal(k.finalPhase,'duke');assert.equal(k.enemies[0].kind,'duke');assert(!k.broadcastSummons.active);assert(!k.storyFlags.martyRescued);}});
test('Both seven-stage routes finish through normal combat with waves, cinema, Spike, Duke and rescue',()=>{const reports=[];for(const kind of ['hero','franklin']){const g=new B.Game();g.franklinUnlocked=kind==='franklin';g.start(null,kind);let ticks=0,retries=0,waves=0,maxSummons=0;const stages=new Set(),bosses=new Set();for(;ticks<120*1500&&g.mode!=='complete';ticks++){if(g.mode==='confrontation')g.finishDukeConfrontation();if(g.mode==='gameover'){retries++;g.retry(true);}if(g.mode==='stageclear')g.finishStageClear();if(g.mode!=='play')continue;stages.add(g.stage);const p=g.p,targets=g.enemies.filter(e=>e.hp>0&&!e.hidden&&e.targetable!==false).concat(g.props.filter(o=>o.kind==='circuit'&&o.hp>0)).sort((a,b)=>Math.hypot(a.x-p.x,(a.y-p.y)*2)-Math.hypot(b.x-p.x,(b.y-p.y)*2));let input={};if(targets.length){const e=targets[0],dx=e.x-p.x,dy=e.y-p.y;if(e.boss)bosses.add(e.kind);input.mx=Math.abs(dx)>62?Math.sign(dx)*(Math.abs(dx)>150?1:.4):0;input.my=Math.abs(dy)>8?Math.sign(dy)*.55:0;input.attackPressed=Math.abs(dx)<122&&Math.abs(dy)<25&&ticks%12===0;input.attackHeld=Math.abs(dx)<116&&Math.abs(dy)<27;if(p.meter>=100&&targets.length>1&&!p.action)input.specialPressed=true;}else input.mx=1;g.step(1/120,input);maxSummons=Math.max(maxSummons,g.enemies.filter(e=>e.broadcastSummon&&e.hp>0).length);for(const event of g.drain())if(event.type==='broadcastWave')waves++;}assert.equal(g.mode,'complete');assert.equal(stages.size,7);assert(g.stats.kos>=71);assert(retries<5);assert(waves>=2);assert(maxSummons<=4);for(const k of ['pizzeria-boss','spike','broadcast-rig','duke'])assert(bosses.has(k));assert(!bosses.has(kind==='franklin'?'franklin':'sherm-slam'));assert(g.storyFlags.martyRescued&&g.storyFlags.broadcastStopped);reports.push({character:kind,seconds:g.t,retries,stages:stages.size,kos:g.stats.kos,broadcastWaves:waves,maxSummons,bosses:[...bosses]});}return reports;});
fs.writeFileSync(path.join(__dirname,'v8-engine-results.json'),JSON.stringify({tests:results,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length},null,2));if(results.some(r=>!r.passed))process.exitCode=1;
