'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),B=require('../engine.js');const tests=[];
function test(name,fn){try{const details=fn();tests.push({name,passed:true,details});console.log('PASS',name);}catch(e){tests.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.message);}}
function arena(stage=0,route='hero'){const g=new B.Game();g.franklinUnlocked=true;g.start(null,route);g.stage=stage;g.activeGate=g.nextGate=2;g.p.x=2200;g.p.y=407;g.camera=1820;g.props=[];g.enemies=[];g.events=[];return g;}
function ticks(g,n,input={}){for(let i=0;i<n;i++)g.step(1/120,input);}
function foe(g,kind){const k=B.EINFO[kind],e={id:++g.enemyId,kind,x:g.p.x+70,y:g.p.y,z:0,face:-1,hp:k.hp,maxHp:k.hp,state:'seek',timer:0,cooldown:999,anim:'idle',animT:0,kb:0,speed:0,variant:0,flashes:0};g.enemies.push(e);return e;}
function resolveMachine(g){const core=g.enemies.find(e=>e.kind==='broadcast-rig');for(let round=1;round<=3;round++){g.updateBroadcastSummons(.01);assert.equal(g.broadcastSummons.wave,round);assert.equal(g.registerHit(core,{damage:999,kb:0}),false);for(const e of g.enemies.filter(e=>e.broadcastSummon&&e.hp>0))g.registerHit(e,{damage:999,kb:0});g.updateBroadcastSummons(.01);assert.equal(g.broadcastSummons.phase,'vulnerable');g.registerHit(core,{damage:999,kb:0});}return core;}
test('Both players knock down once against each of three heavies and recover without death',()=>{for(const route of ['hero','franklin'])for(const kind of ['bear','hippo','pizzeria-boss']){const g=arena(0,route),e=foe(g,kind),hp=e.hp;g.p.face=1;g.p.combo=8;g.setAction('dash');g.hitTest(g.attackSpec('dash'),g.p.action);assert.equal(g.p.action.name,'knockdown');assert.equal(g.p.combo,0);assert(g.p.vx<0);assert.equal(e.hp,hp);const x=g.p.x;g.updateAction(.1,{});ticks(g,125);assert(g.p.x<x);assert.notEqual(g.p.action?.name,'knockdown');const events=g.drain();assert.equal(events.filter(e=>e.type==='playerKnockdown').length,1);assert.equal(events.filter(e=>e.type==='playerDeath').length,0);assert.equal(g.p.lives,3);}});
test('Ordinary enemies retain full Belly Bash/cartwheel launch',()=>{for(const route of ['hero','franklin']){const g=arena(0,route),e=foe(g,'sherm-punch');g.p.face=1;g.setAction('dash');g.hitTest(g.attackSpec('dash'),g.p.action);assert.equal(e.hp,B.EINFO[e.kind].hp-24);assert(e.launchTimer>0);assert.equal(g.p.action.name,'dash');}});
test('Rolling can lands, bounces, traverses release lane, exits and cannot hit twice',()=>{for(const route of ['hero','franklin'])for(const elevation of [0,20,100]){const g=arena(5,route);g.p.z=elevation;const q=g.launchProjectile('trash-can',g.p.x-190,270,g.p.x,g.p.y,20,38,.9);for(let i=0;i<150;i++)g.updateProjectiles(1/120);assert.equal(q.phase,'rolling');assert.equal(q.bounces,1);assert(q.x>g.p.x);assert.equal(g.p.hp,elevation>58?100:80);assert.equal(g.p.action?.name,elevation>58?undefined:'knockdown');for(let i=0;i<600;i++)g.updateProjectiles(1/120);assert(q.done);assert.equal(g.projectiles.length,0);assert.equal(g.p.hp,elevation>58?100:80);}});
test('Spike telegraphs before release and fixes target lane at release, with one can at a time',()=>{const g=arena(5);g.spawnBoss();const e=g.enemies[0];e.entry=null;e.hidden=false;e.state='seek';e.x=2450;e.y=g.p.y;e.cooldown=0;g.updateBoss(e,.01);assert.equal(e.state,'windup');assert.equal(g.projectiles.length,0);const wind=e.move.wind;g.updateBoss(e,wind-.02);assert.equal(g.projectiles.length,0);g.p.y=450;g.updateBoss(e,.03);g.updateBoss(e,.36);assert.equal(g.projectiles.length,1);const q=g.projectiles[0];assert.equal(q.targetY,450);g.p.y=350;g.updateProjectiles(.5);assert.equal(q.y,450);for(let i=0;i<30;i++)assert.notEqual(g.chooseBossMove(e,B.BOSS_DEFINITIONS.spike.moves).area,'trash-can');});
test('Projection phases throw three reels then one remote; attacks destroy three remotes without floor boxes',()=>{const g=arena(4);g.configureProjection();assert(!g.props.some(o=>o.kind==='circuit'));for(let phase=0;phase<3;phase++){let launches=0;for(let i=0;i<6000&&g.projection.phase!=='remote';i++){g.updateProjection(1/120);for(const e of g.drain())if(e.type==='projectile')launches++;}assert.equal(launches,3);const remotes=g.props.filter(o=>o.kind==='remote'&&o.hp>0);assert.equal(remotes.length,1);const o=remotes[0];assert.equal(o.circuitId,phase);g.p.x=o.x-60;g.p.y=o.y;g.p.face=1;g.setAction('palm');g.hitTest(B.HITS.palm,g.p.action);assert.equal(g.projection.circuits[phase].active,false);}assert(g.projection.disabled);assert(!g.projection.active);g.spawnBoss();assert.equal(g.enemies.filter(e=>e.kind==='pizzeria-boss').length,1);assert(!g.spawnBoss());const e=g.enemies[0];for(let i=0;i<400&&e.entry;i++)g.updateEntry(e,1/120);assert.equal(e.entry,null);assert.equal(e.renderScale,1.52);g.registerHit(e,{damage:999,kb:0});ticks(g,150);assert.equal(g.mode,'stageclear');});
test('Three broadcast waves gate core damage; each wave must be fought and final core resolves to Duke',()=>{const g=arena(6);g.spawnBoss();const core=resolveMachine(g);assert.equal(core.hp,0);assert(g.machineDefeated);assert.equal(g.mode,'confrontation');assert.equal(g.stats.kos,10);assert(!g.broadcastSummons.active);assert(!g.storyFlags.martyRescued);g.dukeStaged={x:2380,y:370,face:-1};g.finishDukeConfrontation();const duke=g.enemies[0];assert.equal(duke.x,2380);assert.equal(duke.y,370);assert.equal(duke.entry,null);g.registerHit(duke,{damage:999,kb:0});ticks(g,160);assert.equal(g.mode,'complete');assert(g.storyFlags.martyRescued);});
test('Emergency machine shutdown never deletes living summons, rewards them or permits early Duke',()=>{const g=arena(6);g.spawnBoss();g.updateBroadcastSummons(.01);const live=g.enemies.filter(e=>e.broadcastSummon),ids=live.map(e=>e.id),score=g.score,kos=g.stats.kos;g.stopBroadcastSummons();g.machineDefeated=true;assert(!g.resolveBroadcast());for(const e of live)assert(e.hp>0);assert.deepEqual(g.enemies.filter(e=>e.broadcastSummon).map(e=>e.id),ids);assert.equal(g.score,score);assert.equal(g.stats.kos,kos);g.updateBroadcastSummons(50);assert.equal(g.enemies.filter(e=>e.broadcastSummon).length,2);});
test('Duke frame movement stays physical through all phases and context discourages repeats',()=>{const g=arena(6);g.machineDefeated=true;g.dukeStaged={x:2630,y:324,face:-1};g.finishDukeConfrontation(false);const e=g.enemies[0];let maxDelta=0;for(const ratio of [1,.6,.3]){e.hp=e.maxHp*ratio;for(let i=0;i<1000;i++){const x=e.x,y=e.y;g.p.inv=10;g.updateBoss(e,1/120);const delta=Math.hypot(e.x-x,e.y-y);maxDelta=Math.max(maxDelta,delta);assert(delta<5,'Duke snapped '+delta);}}let repeats=0,last=null,names=new Set();for(let i=0;i<300;i++){g.p.guard=i%3===0;g.p.x=e.x-(i%2?200:65);const m=g.chooseBossMove(e,B.BOSS_DEFINITIONS.duke.moves);if(m.name===last)repeats++;last=m.name;names.add(m.name);}assert.equal(names.size,3);assert(repeats<75);return {maxDelta,repeats};});
test('Boss phase escalation reduces idle intervals while preserving visible telegraphs and punish windows',()=>{const report=[];for(const kind of ['pizzeria-boss','spike','duke']){const stages={'pizzeria-boss':4,spike:5,duke:6};const measurements=[];for(const ratio of [1,.3]){const g=arena(stages[kind]);g.projection.disabled=true;if(kind==='duke'){g.machineDefeated=true;g.finishDukeConfrontation(false);}else g.spawnBoss();const e=g.enemies[0];e.entry=null;e.state='seek';e.hidden=false;e.x=g.p.x+80;e.y=g.p.y;e.cooldown=0;e.hp=e.maxHp*ratio;let attacks=0,recoveryFrames=0,lastState='';for(let i=0;i<7200;i++){g.p.hp=100;g.p.inv=10;g.p.x=e.x-80;g.p.y=e.y;g.updateBoss(e,1/120);if(e.state==='windup'&&lastState!=='windup'){attacks++;assert(e.move.wind>=.6);}if(e.state==='recover')recoveryFrames++;lastState=e.state;}assert(recoveryFrames>0);measurements.push(attacks);}assert(measurements[1]>measurements[0]);report.push({kind,attacksPerMinute:measurements});}assert(report[2].attacksPerMinute[0]>report[0].attacksPerMinute[0]);return report;});
test('Lethal ground/air hits produce one death and one respawn; knockdown cannot consume extra life',()=>{for(const z of [0,30]){const g=arena(),e=foe(g,'hippo');g.p.z=z;g.p.hp=1;g.damagePlayer(e);assert.equal(g.p.hp,0);assert(!g.knockdown(-1));ticks(g,285);assert.equal(g.p.lives,2);assert.equal(g.p.hp,100);assert.equal(g.drain().filter(e=>e.type==='playerDeath').length,1);}});
fs.writeFileSync(__dirname+'/v9-engine-results.json',JSON.stringify({tests,passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed).length},null,2));process.exitCode=tests.some(t=>!t.passed)?1:0;
